<div class="wrapper">
    <div class="wrapper-title">
        <?php echo lang('add-new-custom-field')?>
        <span><?php echo lang('add-new-custom-field-note')?></span>
    </div>
    <div class="wrapper-content">

        <div class=""><?php echo ($message)? $message : null?></div>
        <form class="col s12" action="" method="post">
			<?php CSRFProtection::embed() ?>
            <div class="form-group row">
                <div class="col-sm-5">
                    <h6><?php echo lang('custom-field-title')?></h6>
                    <p class="form-description">
                        <?php echo lang('custom-field-title-description')?>
                    </p>
                </div>
                <div class="col-sm-7">
                    <?php foreach(get_all_languages() as $language):?>
                        <input class="form-control" type="text" name="val[title][<?php echo $language['language_id']?>]" placeholder="<?php echo lang('custom-field-title')?>"/><br>
                        <span><?php echo $language['language_title']?></span>
                    <?php endforeach?>
                </div>
            </div>
            <div class="divider"></div>

            <div class="form-group row">
                <div class="col-sm-5">
                    <h6><?php echo lang('custom-field-category')?></h6>
                    <p class="form-description"><?php echo lang('custom-field-category-description')?></p>
                </div>
                <div class="col-sm-7">
                    <select class="c-select" name="val[category_id]">
                        <?php foreach(get_custom_field_categories($type) as $category):?>
                            <option value="<?php echo $category['id']?>"><?php echo lang($category['title'])?></option>
                        <?php endforeach?>
                    </select>
                </div>
            </div>
            <div class="divider"></div>
            <div class="form-group row">
                <div class="col-sm-5">
                    <h6><?php echo lang('custom-field-description')?></h6>
                    <p class="form-description"><?php echo lang('custom-field-description-note')?></p>
                </div>
                <div class="col-sm-7">
                    <?php foreach(get_all_languages() as $language):?>
                        <input class="form-control" type="text" name="val[description][<?php echo $language['language_id']?>]" placeholder="<?php echo lang('custom-field-description')?>"/><br>
                        <span><?php echo $language['language_title']?></span>
                    <?php endforeach?>

                </div>
            </div>
            <div class="divider"></div>
            <div class="form-group row">
                <div class="col-sm-5">
                    <h6><?php echo lang('custom-field-type')?></h6>
                    <p class="form-description">
                        <?php echo lang('custom-field-type-description')?>
                    </p>
                </div>
                <div class="col-sm-7">
                    <select class="c-select" id="custom-field-type-selection" name="val[field_type]">
                        <option value="text">Text</option>
                        <option value="longtext">Long Text</option>
                        <option value="selection">Selection</option>
                        <option value="boolean">True/False</option>
                    </select>

                    <textarea id="custom-field-selection-data" style="display: none" class="materialize-textarea" placeholder="Selection data" name="val[data]"></textarea><br/>
                </div>
            </div>

            <div class="divider"></div>
            <div class="form-group row">
                <div class="col-sm-5">
                    <h6><?php echo lang('include-in-registration')?></h6>
                    <p class="form-description"><?php echo lang('include-in-registration-description')?></p>
                </div>
                <div class="col-sm-7">
                    <select class="c-select" name="val[show_in_form]">
                        <option value="0"><?php echo lang('no')?></option>
                        <option value="1"><?php echo lang('yes')?></option>
                    </select>
                </div>
            </div>
            <div class="divider"></div>
            <div class="form-group row">
                <div class="col-sm-5">
                    <h6><?php echo lang('required')?></h6>
                    <p class="form-description"><?php echo lang('custom-field-required-description')?> </p>
                </div>
                <div class="col-sm-7">
                    <select class="c-select" name="val[required]">
                        <option value="0"><?php echo lang('no')?></option>
                        <option value="1"><?php echo lang('yes')?></option>
                    </select>
                </div>
            </div>
            <div class="divider"></div>
            <div class="form-group row">
                <div class="col-sm-5"></div>
                <div class="col-sm-7">
                    <button class="btn red lighten-3"><?php echo lang('add-field')?></button>
                </div>
            </div>
        </form>
    </div>
</div>