<div id="main-wrapper" style="margin: 0;padding: 0">


    <?php if(config('homepage-member-list', true)):?>
        <div id="home-members">
            <div class="container clearfix" id="members">
                <?php foreach(get_latest_users(10) as $user):?>
                    <a href="<?php echo profile_url(null, $user)?>" style="background-image: url(<?php echo get_avatar(200, $user)?>)"></a>
                <?php endforeach?>
            </div>
        </div>
    <?php endif?>
</div>