<?php
$user = isset($app->profileUser) ? $app->profileUser : get_user();
$friendViewers = get_friends();
$privacy = get_privacy_details($user['id']);
$privacyViews = isset($privacy['who_can_see_visitors']) ? $privacy['who_can_see_visitors'] : "";
$viewblock = false;
if($privacyViews == '1')
{
    $link = url_to_pager('lastvisitor', array('id' => $user['username'])) . "?jsi={$user['id']}";
    $viewblock = true;
}
else if(!empty($friendViewers) && ($privacyViews == '2'))
{
    $link = url_to_pager('lastvisitor', array('id' => $user['username'])) . "?jsi={$user['id']}";
    $viewblock = true;
}
else if($user['id'] == get_userid())
{
    $link = url_to_pager('lastvisitor', array('id' => $user['username'])) . "?jsi={$user['id']}";
    $viewblock = true;
}
else
{
    $link = '#';
    $viewblock = false;
}
$users = ($user) ? get_last_visitors($user['id'], $limit) : null;
?>
<?php if($users && $viewblock):?>
    <div class="box lastvisitor-listings-box">
        <div class="title"><?php _lang('lastvisitor::headingname')?>
            <a ajax="true" href="<?php echo $link ?>" class="more-link pull-right"><i class="ion-ios-arrow-forward"></i></a></div>
        <div class="clearfix">
            <?php foreach($users as $userid):?>
                <?php
                    if($choosegender && !$withavatar) $user = lastvisitor_find_user($userid['viewer_id'], $userid['gender'], true, false);
                    else if(!$choosegender && $withavatar) $user = lastvisitor_find_user($userid['viewer_id'], $userid['gender'], false, true);
                    else if($choosegender && $withavatar) $user = lastvisitor_find_user($userid['viewer_id'], $userid['gender'], true, true);
                    else $user = lastvisitor_find_user($userid['viewer_id']);
                ?>
                <?php if($user):?>
                <a href="<?php echo profile_url(null, $user)?>" ajax="true" class="lastvisitor-listing " style="background-image: url(<?php echo get_avatar(200, $user)?>)">
                    <h6 class="name"><?php echo get_user_name($user) . "<br /> " . AgoMin($userid['view_date'], true)?></h6>
                </a>
                <?php endif ?>
            <?php endforeach?>
        </div>
    </div>
<?php endif?>