<div class="box">
    <ul class="menu">

    </ul>
    <div class="global-filter-container" data-url="<?php echo url('blogs')?>">
        <div class="row">
            <div class="col-sm-6">
                <h3><?php _lang('blog::blogs')?></h3>
            </div>
            <div class="col-sm-6">
                <form id="video-list-search" method="post" onsubmit=" return run_global_filter()" action="" class="form-inline pull-right">
				<?php CSRFProtection::embed() ?>
                    <input type="hidden" class="video-type-input filter-input" data-name="type" value="<?php echo input('type','browse')?>"/>
                    <input value="<?php echo input('term')?>" type="text" class="form-control filter-input" data-name="term" placeholder="<?php _lang('blog::find-blogs')?>"/>
                    <button class="btn btn-info"><i class="ion-search"></i></button>
                </form>
            </div>
        </div>
        <div class="  filter-pane">
            <select id="video-category-list" onchange="return run_global_filter()" data-name="category" class="c-select filter-input" >
                <option <?php echo (input('category', 'all') == 'all') ? 'selected'  : null?>  value="all"><?php _lang('blog::all-categories')?></option>
                <?php foreach(get_blog_categories() as $category):?>
                    <option <?php echo (input('category', 'all') == $category['id']) ? 'selected'  : null?> value="<?php echo $category['id']?>"><?php _lang($category['title'])?></option>
                <?php endforeach?>

            </select>

            <select id="video-filter-select" onchange="return run_global_filter()" data-name="filter" class="c-select filter-input">
                <option value="all"><?php _lang('all')?></option>
                <option <?php echo (input('filter') == 'top') ? 'selected' : null?> value="top"><?php _lang('video::top')?></option>
                <option <?php echo (input('filter') == 'featured') ? 'selected' : null?> value="featured"><?php _lang('video::featured')?></option>
            </select>
            <div class="list-layout-type">
                <a href="" onclick="return change_listing_layout('#blogs-list-container', 'list')"><i class="ion-ios-list-outline"></i></a>
                <a href="" onclick="return change_listing_layout('#blogs-list-container', 'grid')"><i class="ion-android-apps"></i></a>
            </div>
        </div>
    </div>
    <div id="blogs-list-container" class="box-content clearfix grid-listing-container">
        <?php foreach($blogs->results() as $blog):$user = find_user($blog['user_id'])?>
            <div class="each-item clearfix">
                <div class="left">
                    <?php if($blog['featured']):?>
                        <span class="featured-tag"><?php _lang('featured')?></span>
                    <?php endif?>
                    <a ajax="true" href="<?php echo url('blog/'.$blog['slug'])?>" style="background-image:url(<?php echo ($blog['image']) ? url_img($blog['image'], 700) : get_avatar(200, $user)?>)"></a>
                </div>

                <div class="right">
                    <span class="item-title"><a ajax="true" href="<?php echo url('blog/'.$blog['slug'])?>"><?php echo $blog['title']?></a> </span>
                    <div class="item-info">
                        <span class="help-block" style="display: block">
                                    <?php _lang('blog::posted-by')?> : <a href="<?php echo profile_url(null, $user)?>"><?php echo get_user_name($user)?></a>
                            <?php _lang('blog::on')?> <?php echo date('M j , y  h:i A', $blog['time'])?>
                                </span>

                    </div>
                    <p class="item-desc"><?php echo strip_tags(str_limit($blog['content'], 100))?></p>
                </div>
            </div>

        <?php endforeach?>



    </div>

    <div class="box-content">
        <?php if($blogs->total):?>

            <?php echo $blogs->append(array('category' => input('category'), 'type' => input('type', 'browse'), 'term' => input('term'), 'filter' => input('filter', 'all')))->links()?>
        <?php else:?>

            <div class="alert alert-info"><?php _lang('blog::blogs-list-empty')?></div>
        <?php endif?>
    </div>

</div>