<?php if(config('homepage-member-list', true)):?>
    <div id="home-members">
        <div class="container"><h4><?php _lang('latest-members')?></h4></div>
        <div class="container clearfix" id="members">
            <?php foreach(get_latest_users($limit) as $user):?>
                <a href="<?php echo profile_url(null, $user)?>" style="background-image: url(<?php echo get_avatar(200, $user)?>)"></a>
            <?php endforeach?>
        </div>
    </div>
<?php endif?>