<?php if(is_loggedIn()):$activities = getActivities($settings['limit'])?>
    <?php if($activities->total):?>
        <div class="box">
            <div class="title"><?php _lang('activity::activities')?></div>
            <div class="box-content slimscroll" data-height="250px" >
                <?php foreach($activities->results() as $activity):?>
                    <?php echo view('activity::activity', array("activity" => $activity))?>
                <?php endforeach?>
            </div>
        </div>
    <?php endif?>
<?php endif?>