<div class="box">
    <?php if($message): ?>
        <div class="alert alert-success"><?php _lang('photo::photo-created')?></div>
    <?php endif ?>
    <div class="global-filter-container" data-url="">
        <div class="row">
            <div class="col-sm-6">
                <h3><?php _lang('photo::add-new-photo')?></h3>
            </div>
        </div>
    </div>
    <div class="box-content" style="padding: 20px 10%">
        <form data-error="Something went wrong. try again" action="" method="post" enctype="multipart/form-data">
			<?php CSRFProtection::embed() ?>
			<input type="hidden" name="val[user_id]" value="<?php echo input('id', get_userid())?>"/>
            <input type="hidden" name="val[entity_id]" value="<?php echo get_userid()?>"/>
            <input type="hidden" name="val[entity_type]" value="user"/>
            <!--
            <div class="form-group row">
                <label class="control-label col-sm-4"><?php _lang('photo::photo-title')?></label>
                <div class="col-sm-8">
                    <input type="text" name="val[name]" class="form-control" placeholder="<?php _lang('photo::photo-title')?>" required=""/>
                </div>
            </div>
            <div class="form-group row">
                <label class="control-label col-sm-4"><?php _lang('photo::photo-description')?></label>
                <div class="col-sm-8">
                    <textarea name="val[description]" data-height="100px" style="height: 100px" class="form-control auto-grow-input" placeholder="<?php _lang('photo::photo-description')?>"></textarea>
                </div>
            </div>
            -->
            <div class="form-group row">
                <label class="control-label col-sm-4"><?php _lang('photo::photo-privacy')?></label>
                <div class="col-sm-8">
                    <select name="val[privacy]" class="c-select">
                        <option <?php echo (config('default-photo-album-privacy', 1) == 1) ? 'selected' : null?> value="1"><?php _lang('public')?></option>
                        <option <?php echo (config('default-photo-album-privacy', 1) == 2) ? 'selected' : null?> value="2"><?php echo (config('relationship-method', 3) == 1) ? lang('feed::followers-only') : lang('feed::friends-only')?></option>
                        <option <?php echo (config('default-photo-album-privacy', 1) == 3) ? 'selected' : null?> value="3"><?php echo lang('feed::only-me')?></option>
                    </select>
                </div>
            </div>
            <div class="form-group row">
                <label class="control-label col-sm-4"><?php _lang('photo::select-photo')?></label>
                <div class="col-sm-8">
                    <input name="image" class="form-control form-control-lg" type="file"/>
                </div>
            </div>
            <button class="btn btn-primary" required=""><?php _lang('photo::add-photo')?></button>
        </form>
    </div>
</div>