<div id="photos-list-container" class="box box-content clearfix <?php echo (config('default-photo-list-type', 'list') != 'list') ? 'list-listing-container' : 'grid-listing-container'?>">
    <div class="global-filter-container" data-url="">
        <div class="row">
            <div class="col-sm-6"><h3><?php _lang('photo::my-photos')?></h3></div>
            <!--
            <div class="col-sm-6">
                <form id="photo-list-search" method="post" onsubmit=" return run_global_filter()" action="" class="form-inline pull-right">
					<?php CSRFProtection::embed() ?>
                    <input type="hidden" class="photo-type-input filter-input" data-name="type" value="<?php echo input('type','browse')?>"/>
                    <input value="<?php echo input('term')?>" type="text" class="form-control filter-input" data-name="term" placeholder="<?php _lang('photo::search-photos')?>"/>
                    <button class="btn btn-info"><i class="ion-search"></i></button>
                </form>
            </div>
            -->
        </div>
        <!--
        <div class="  filter-pane">
            <div class="list-layout-type">
                <a href="" onclick="return change_listing_layout('#photos-list-container', 'list')"><i class="ion-ios-list-outline"></i></a>
                <a href="" onclick="return change_listing_layout('#photos-list-container', 'grid')"><i class="ion-android-apps"></i></a>
            </div>
        </div>
          -->
    </div>
    <div id="photos-list" class="box photos-list photo-directory" data-type="user-all" data-id="<?php echo get_userid() ?>" data-offset="0" style="margin: 0px;box-shadow: 0px 0px 0px #FFFFFF;border-radius: 0px;border: none;">
        <div class="photo upload-photo" style="vertical-align: top;">
            <form data-error="Something went wrong. try again" action="" method="post" enctype="multipart/form-data">
				<?php CSRFProtection::embed() ?>
                <span class="file-input"><input  onchange="upload_photos()" multiple type="file" id="photo-upload-input" name="photos[]"/></span>
                <a onclick="return file_chooser('#photo-upload-input')" href=""><i  class="ion-ios-cloud-upload-outline"></i><span><?php echo lang('photo::add-photos')?></span></a>
            </form>
            <div class="indicator"><img src="<?php echo img('images/loading.gif')?>"/> <?php _lang('photo::uploading')?><span>0%</span></div>
        </div>
        <?php foreach($myphotos as $photo): ?>
        <?php $user = find_user($photo['user_id']); $username = $user['username']; $first_name = $user['first_name']; $last_name = $user['last_name']; $user_name = "$first_name $last_name"; $user_name = trim($user_name) == '' ? $username : $user_name; ?>
        <div class="photo"><a data-image="<?php echo url_img($photo['path'], 920) ?>" data-id="<?php echo $photo['id'] ?>" class="image photo-viewer" style="background-image:url(<?php echo url_img($photo['path'], 600) ?>)" href=""></a></div>
        <?php endforeach?>
    </div>
    <a id="photos-list-indicator" href="" onclick="return paginate_album_photos()" class="title" style="display: block;text-align: center"><?php _lang('view-more')?> <img src="<?php echo img('images/loading.gif')?>" style="width: 10px;display: none"/></a>
</div>