<div class="modal" id="photoViewer" data-backdrop="true" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog viewer-container" role="document">
        <div class="modal-content clearfix">
            <div class="viewer-left">

            </div>
            <div class="viewer-right slimscroll" data-height="100%">

            </div>
        </div>

        <button type="button" class="close"  data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            <span class="sr-only">Close</span>
        </button>
    </div>
</div>