<div class="wrapper">
    <div class="wrapper-title">
        <p><?php echo lang('forum::add-tag') ?></p>
        <span><?php echo lang('forum::add-tag-desc') ?></span>
    </div>
    <div class="wrapper-content">
        <?php if($messages != null): ?>
        <div class="alert alert-danger"><?php echo $messages ?></div>
        <?php endif ?>
        <form action="" class="adm" method="post">
            <?php CSRFProtection::embed() ?>
            <div class="form-group row">
                <label for="val[title]" class="col-sm-3 form-control-label"><?php echo lang('forum::tag-title')?>: </label>
                <div class="col-sm-9">
                        <input class="form-control" type="text" name="val[title]" placeholder="<?php echo lang('forum::tag-title')?>" /><br>
                </div>
            </div>
            <div class="form-group row">
                    <label for="val[color]" class="col-sm-3 form-control-label"><?php echo lang('forum::tag-color') ?>: </label>
                <div class="col-sm-9">
                    <input name="val[color]" type="text" class="form-control color-picker" placeholder="<?php echo lang('forum::tag-color')?>" />
                </div>
            </div>
            <div class="row">
                <div class="col-sm-5"></div>
                <div class="col-sm-7">
                    <input type="submit" value="Add" class="btn btn-info" />
                </div>
            </div>
			<input type="hidden" name="val[type]" value="add_tag" />
        </form>
    </div>
</div>';