<div class="wrapper">
    <div class="wrapper-title">
        <?php _lang('blog::manage-categories')?>
         - <a class="btn btn-success" href="<?php echo url_to_pager('admincp-blog-categories-add')?>"><?php _lang('blog::add-category')?></a>
    </div>
    <div class="wrapper-content">
        <table class="table">
            <thead>
                <tr>
                    <th>ID</th>
                    <th><?php _lang('title')?></th>
                    <th><?php _lang('actions')?></th>
                </tr>
            </thead>
            <tbody data-url="<?php echo url_to_pager('admincp-blog-manage-category').'?action=order'?>" class="admincp-sortable" style="position: relative">
            <?php foreach($categories as $category):?>
                <tr style="" class="item" id="<?php echo $category['id']?>">
                    <td style="width: 10%"><?php echo $category['id']?></td>
                    <td style="width: 30%"><?php _lang($category['title']) ?></td>

                    <td style="width: 20%">
                        <a class="btn btn-sm btn-success" href="<?php echo url_to_pager('admincp-blog-manage-category').'?action=edit&id='.$category['id']?>"><?php _lang('edit')?></a>
                        <a class="btn btn-sm btn-danger admin-confirm" href="<?php echo url_to_pager('admincp-blog-manage-category').'?action=delete&id='.$category['id']?>"><i class="ion-android-delete"></i></a>
                    </td>
                </tr>
            <?php endforeach?>
            </tbody>
        </table>
    </div>
</div>