<div class="row" style="margin: 0">
    <div class="col s5">
        <h6><?php echo $setting['title']?></h6>
        <p class="form-description"><?php echo $setting['description']?></p>
    </div>
    <div class="col s7">
        <div class="input-field ">
            <?php if($setting['type'] == 'text'):?>
                <input class="form-control" id="<?php echo $key?>" type="text" value="<?php echo (isset($value[$key])) ? $value[$key] : $setting['value']?>" name="val[<?php echo $key?>]" placeholder="<?php echo $setting['title']?>"/>
            <?php elseif($setting['type'] == "textarea"):?>
                <textarea class="form-control" id="<?php echo $key?>" name="val[<?php echo $key?>]" placeholder="<?php echo $setting['title']?>"><?php echo (isset($value[$key])) ? $value[$key] : $setting['value']?></textarea>
            <?php elseif($setting['type'] == "selection"):?>
                <?php if(isset($setting['data']) and is_callable($setting['data'])) {
                    $data = call_user_func($setting['data']);
                } else {
                    $data = $setting['data'];

                }

                $v = (isset($value[$key])) ? $value[$key] : $setting['value'];
                ?>
                <select class="c-select" id="<?php echo $key?>" name="val[<?php echo $key?>]">
                    <?php foreach($data as $k => $v):?>

                        <option <?php echo ($v == $k) ? 'selected':null?> value="<?php echo $k?>"><?php echo   $v?></option>
                    <?php endforeach?>
                </select>
            <?php elseif($setting['type'] == "boolean"):?>

                <select class="c-select" id="<?php echo $key?>" name="val[<?php echo $key?>]" class="browser-default">
                    <?php $v = (isset($value[$key])) ? $value[$key] : $setting['value'];?>
                    <option <?php echo ($v == 1) ? 'selected':null?> value="1"><?php echo lang('yes')?></option>
                    <option <?php echo ($v == 0) ? 'selected':null?> value="0"><?php echo lang('no')?></option>
                </select>

            <?php endif?>
        </div>
    </div>
</div>