<div class="wrapper">
    <div class="wrapper-title">
        <?php _lang('video::video-categories')?>
    </div>
    <div class="wrapper-content">
        <form class="wrapper-form" method="post" action="">
			<?php CSRFProtection::embed() ?>
            <div class="form-group row">
                <label class="col-sm-3 form-control-label"><?php _lang('video::category-title')?></label>
                <div class="col-sm-9">
                    <label>(English)</label>
                    <input type="text" name="val[title][english]" value="<?php echo get_phrase('english', $category['title'])?>" class="form-control" placeholder="<?php _lang('video::category-title')?>"/>
                    <a href="" class="other-languages-link"  onclick="return show_other_languages('#video-category-info-other-languages')"><?php _lang('edit-other-languages')?></a>
                    <div class="other-languages" id="video-category-info-other-languages">
                        <?php foreach(get_all_languages() as $language):?>
                            <?php if($language['language_id'] != 'english'):?>
                                <input class="form-control" value="<?php echo get_phrase($language['language_id'], $category['title'])?>"   type="text" name="val[title][<?php echo $language['language_id']?>]" placeholder="<?php _lang('video::category-title')?>"/><br>
                                <p class="help-block"><?php echo $language['language_title']?></p>
                            <?php endif?>
                        <?php endforeach?>
                    </div>

                </div>


            </div>
            <div class="form-group row">
                <label class="col-sm-3 form-control-label"><?php _lang('video::parent-category')?></label>
                <div class="col-sm-9">
                    <select class="c-select" name="val[category]">
                        <option value="0"><?php _lang('video::none')?></option>
                        <?php foreach(get_video_categories() as $cat):?>
                            <option <?php echo ($cat['id'] == $category['parent_id']) ? 'selected' : null?> value="<?php echo $cat['id']?>"><?php _lang($cat['title'])?></option>
                        <?php endforeach?>
                    </select>

                </div>
            </div>

            <button class="btn btn-info"><?php _lang('save-category')?></button>
        </form>
    </div>
</div>