<div class="box">
    <div class="title"><?php _lang('edit')?></div>
    <div class="box-content" style="padding: 20px 10%">
        <?php if($message):?>
            <div class="alert alert-danger"><?php echo $message?></div>
        <?php endif?>
        <form action="" method="post">
            <?php CSRFProtection::embed() ?>
            <div class="form-group row">
                <label class="control-label col-sm-4"><?php _lang('group::group-title')?></label>
                <div class="col-sm-8">
                    <input value="<?php echo get_group_details('group_title')?>" type="text" name="val[group_title]" class="form-control"/>
                </div>
            </div>



            <div class="form-group row">
                <label class="control-label col-sm-4"><?php _lang('group::description')?></label>
                <div class="col-sm-8">
                    <textarea name="val[group_description]" class="form-control auto-grow-input"><?php echo $app->profileGroup['group_description']?></textarea>
                </div>
            </div>

            <div class="form-group row">
                <label class="control-label col-sm-4"><?php _lang('privacy')?></label>
                <div class="col-sm-8">
                    <select class="c-select" name="val[privacy]">
                        <option value="1" <?php echo (get_group_details('privacy') == 1) ? 'selected' : null?>><?php _lang('public')?></option>
                        <option value="2" <?php echo (get_group_details('privacy') == 2) ? 'selected' : null?>><?php _lang('private')?></option>
                    </select>
                    <p class="help-block">
                    <p><strong><?php _lang('public')?>: </strong>
                        <?php _lang('group::group-public-note')?></p>
                    <p>
                        <strong><?php _lang('private')?>: </strong>
                        <?php _lang('group::group-private-note')?>
                    </p>
                    </p>
                </div>
            </div>

            <div class="form-group row">
                <label class="control-label col-sm-4"><?php _lang('group::group-who-can-post')?></label>
                <div class="col-sm-8">
                    <select class="c-select" name="val[who_can_post]">
                        <option value="1" <?php echo (get_group_details('who_can_post') == 1) ? 'selected' : null?>><?php _lang('group::members')?></option>
                        <option value="2" <?php echo (get_group_details('who_can_post') == 2) ? 'selected' : null?>><?php _lang('group::moderators-admins')?></option>
                        <option value="3" <?php echo (get_group_details('who_can_post') == 3) ? 'selected' : null?>><?php _lang('group::admins')?></option>
                    </select>

                </div>
            </div>

            <div class="form-group row">
                <label class="control-label col-sm-4"><?php _lang('group::group-who-can-add-member')?></label>
                <div class="col-sm-8">
                    <select class="c-select" name="val[who_can_add_member]">
                        <option value="1" <?php echo (get_group_details('who_can_add_member') == 1) ? 'selected' : null?>><?php _lang('group::members')?></option>
                        <option value="2" <?php echo (get_group_details('who_can_add_member') == 2) ? 'selected' : null?>><?php _lang('group::moderators-admins')?></option>
                        <option value="3" <?php echo (get_group_details('who_can_add_member') == 3) ? 'selected' : null?>><?php _lang('group::admins')?></option>
                    </select>

                </div>
            </div>


            <button class="btn btn-secondary"><?php _lang('save')?></button>

            <a href="javascript::void(0)" onclick="return confirm.url('<?php echo url_to_pager('group-delete', array('id' => $app->profileGroup['group_id']))?>')" class="btn btn-danger pull-right"><?php _lang('delete')?></a>
        </form>
    </div>
</div>