<div class="media media-md">
    <?php
        $email = $contact['email'];
        $q = db()->query("SELECT id,username,first_name,last_name,bio,avatar FROM users WHERE email_address='{$email}' OR social_email='{$email}'");
        $user = $q->fetch_assoc();
        $name = $contact['name'];
        $avatar = ($contact['avatar']) ? $contact['avatar'] : img('images/avatar.png');
        if($user) {
            $name = get_user_name($user);
            $avatar  = get_avatar(75, $user);
        }
    ?>
    <div class="media-left">
        <div class="media-object">
            <img src="<?php echo $avatar?>"/>
        </div>
    </div>
    <div class="media-body">
        <h6><?php echo $name?></h6>

        <?php if($user):?>
            <?php if(plugin_loaded('relationship')):?>
                <span class="pull-right">
                    <?php echo view('relationship::button', array('userid' => $user['id']))?>
                </span>
            <?php endif?>
        <?php else:?>
            <?php if($type  == 'gmail'):?>
                <div class="clearfix">
                    <p class="help-block pull-left" style="width: 60%"><?php echo $email?></p>
                    <button data-email="<?php echo $email?>" onclick="return social_invite_user(this)" class="btn btn-default btn-sm pull-right social-invite-button"><?php _lang('social::invite')?></button>
                </div>
            <?php else:?>

            <?php endif?>
        <?php endif?>
    </div>
</div>