<div id="topo">
    <?php if(!isMobile()):?>
        <div id="slides">
            <div class="slide slide-1"></div>
            <div class="slide slide-2"></div>
            <div class="slide slide-3"></div>
        </div>
    <?php endif?>
    <div id="topo-content">
        <div class="container">


            <div class="row" style="">
                <div class="col-sm-7"  id="welcome-notes">

                    <h2 class="big"><?php _lang('welcome')?> <span><?php  _lang('to-our')?> <?php echo config('site_title')?></span></h2>

                    <div id="home-social-notes">
                        <?php _lang('welcome-note')?>
                    </div>

                    <div class="social-icons">
                        <i class="ion-chatboxes"></i>
                        <i class="ion-ios-compose-outline"></i>
                        <i class="ion-ios-people-outline"></i>
                    </div>
                </div>

                <div id="home-login-container" class="col-sm-5">
                    <div class="login-content">
                        <?php if(config('user-signup', true)):?>
                            <div class="title media">
                                <a  href="<?php echo url_to_pager('signup')?>" class="pull-right btn btn-secondary btn-block btn-upper"><?php _lang('signup-for-account')?></a>
                            </div>
                        <?php endif?>
                        <div class="content">
                            <form action="<?php echo url_to_pager('login')?>" method="post">
                                <?php CSRFProtection::embed() ?>
                                <fieldset class="form-group">
                                    <input name="val[username]" type="text" class="form-control" placeholder="<?php _lang('username-email-address')?>"/>
                                </fieldset>
                                <fieldset class="form-group">
                                    <div class="input-group">
                                        <input type="password" class="form-control input-lg" name="val[password]" placeholder="<?php _lang('your-password')?>">
                                        <div class="input-group-addon"><a  href="<?php echo url_to_pager('forgot-password')?>"><?php _lang('forgot')?></a> </div>
                                    </div>
                                </fieldset>
                                <div class="clearfix">
                                    <div class="pull-left">
                                        <button class="btn btn-info btn-upper"><?php _lang('sign-in')?></button>
                                    </div>
                                    <div class="checkbox pull-right">
                                        <label class="c-input c-checkbox">
                                            <input name="val[remember]" checked type="checkbox">
                                            <span class="c-indicator"></span>
                                            <?php _lang('remember-me')?>
                                        </label>
                                    </div>
                                </div>
                            </form>
                        </div>
                        <?php if(config('enable-facebook', false) || config('enable-twitter', false) || config('enable-googleplus', false) || config('enable-vk', false)): ?>
                        <div id="social-links-container">
                            <div class="sign-with-container">
                                <div class="text"><?php _lang('login-with')?></div>
                                <div class="line"></div>
                            </div>
                            <div class="content">
                                <ul id="home-social-links">
                                    <?php if(config('enable-facebook', false)):?>
                                    <li><a class="facebook" href="<?php echo url_to_pager('facebook-auth')?>"><i class="icon ion-social-facebook"></i> </a></li>
                                    <?php endif?>
                                    <?php if(config('enable-twitter', false)):?>
                                    <li><a class="twitter" href="<?php echo url_to_pager('twitter-auth')?>"><i class="icon ion-social-twitter"></i> </a> </li>
                                    <?php endif?>
                                    <?php if(config('enable-googleplus', false)):?>
                                    <li><a class="googleplus" href="<?php echo url_to_pager('googleplus-auth')?>"><i class="ion-social-googleplus-outline"></i> </a> </li>
                                    <?php endif?>
                                    <?php if(config('enable-vk', false)):?>
                                    <li><a class="vk" href="<?php echo url_to_pager('vk-auth')?>"><i class="ion-android-arrow-forward"></i> </a> </li>
                                    <?php endif?>

                                    <?php echo fire_hook('extend.third.party.auth',null,array());?>
                                </ul>
                            </div>
                        </div>
                        <?php endif ?>
                   </div>
                    </div>
            </div>
        </div>
    </div>
</div>