<div class="box ">
    <?php if(user_has_permission('can-add-music') && is_loggedIn()): ?>
    <div class="box-content">
        <a href="<?php echo url_to_pager('music-create') ?>" ajax="true" class="btn btn-block btn-secondary"><i class="ion-ios-plus-empty"></i> <?php echo lang('music::add-new-music') ?></a>
    </div>
    <?php endif ?>
    <ul class="menu">
        <?php foreach(get_menus("musics-menu") as $menu): ?>
        <li><a ajax="true" href="<?php echo $menu->link ?>"><?php echo lang($menu->title) ?></a> </li>
        <?php endforeach ?>
        <li><a ajax="true" href="<?php echo url_to_pager('musics')?>"><?php echo lang('music::musics')?></a></li>
        <?php if(is_loggedIn()): ?>
        <li><a ajax="true" href="<?php echo url('musics?type=mine') ?>"><?php echo lang('music::my-musics') ?></a> </li>
        <?php endif ?>
        <li><a ajax="true" href="<?php echo url_to_pager('music-playlists')?>"><?php echo lang('music::playlists')?></a></li>
    </ul>
</div>