<div class="box">
    <div class="title"><?php _lang('about')?> <?php echo get_user_name(app()->profileUser)?></div>
    <div class="box-content">
        <div class="row">
            <div class="col-sm-5">
                <ul>
                    <li><a href="<?php echo profile_url('about?type=overview', app()->profileUser)?>"><?php _lang('overview')?></a> </li>
                    <?php foreach( get_custom_field_categories("user") as $category):?>
                        <li><a href="<?php echo profile_url('about?type='.$category['id'], app()->profileUser)?>"><?php _lang($category['title'])?></a> </li>
                    <?php endforeach?>
                </ul>
            </div>
            <div class="col-sm-7">
                <?php if($type == 'overview'):?>
                    <ul>

                        <?php if(config('enable-last-seen', true)):?>
                            <li><span class="online-status <?php echo get_online_status_icon($app->profileUser) ?>"></span>
                                <span style="margin-left:10px;color:grey !important"><span style="color:#ABACAD !important;font-weight:normal !important" class="timeago " title="<?php echo date('c', $app->profileUser['online_time'])?>"><?php echo date('c', $app->profileUser['online_time'])?></span></span>
                            </li>
                        <?php endif?>
                        <?php if($app->profileUser['country']):?>
                            <li><span><i class="ion-ios-location"></i> <?php _lang('from')?></span>
                                <?php echo (app()->profileUser['city']) ? app()->profileUser['city'].',' : null?>
                                <?php echo (app()->profileUser['state']) ? app()->profileUser['state'].',' : null?>
                                <?php echo ucwords(app()->profileUser['country'])?>
                            </li>
                        <?php endif?>
                        <li><span><i class="<?php echo (app()->profileUser['gender'] == 'male') ? 'ion-man' : 'ion-woman'?>"></i></span> <?php echo ucwords(lang(app()->profileUser['gender']))?></li>
                        <?php if(config('enable-birthdate', true)):?>
                            <li><span><i class="ion-android-calendar"></i></span>
                                <?php echo app()->profileUser['birth_day']?>,
                                <?php echo lang(app()->profileUser['birth_month'])?>
                                <?php if(can_view_birthdate($app->profileUser)):?>
                                    ,<?php echo app()->profileUser['birth_year']?>
                                <?php endif?>
                            </li>
                        <?php endif?>

                        <?php if($app->profileUser['bio']):?>
                            <li><span><i class="ion-ios-information-outline"></i> <?php _lang('bio')?></span> <?php echo output_text(app()->profileUser['bio'])?></li>
                        <?php endif?>

                    </ul>
                <?php else:?>
                    <?php foreach(get_custom_fields('user', $type) as $field):?>
                        <?php if(get_user_data($field['title'], app()->profileUser)):?>
                            <ul>
                                <li><strong><?php _lang($field['title'])?> : </strong> <?php echo get_user_data($field['title'], app()->profileUser)?></li>
                            </ul>
                        <?php endif?>

                    <?php endforeach?>
                <?php endif?>
            </div>
        </div>
    </div>
</div>