<div class="box">
    <div class="global-filter-container" data-url="<?php echo url('groups')?>">
        <div class="row">
            <div class="col-sm-6">
                <h3><?php _lang('group::groups')?></h3>
            </div>
            <div class="col-sm-6">
                <form id="video-list-search" method="post" onsubmit=" return run_global_filter()" action="" class="form-inline pull-right">
					<?php CSRFProtection::embed() ?>
                    <input type="hidden" class="video-type-input filter-input" data-name="type" value="<?php echo input('type','recommend')?>"/>
                    <input value="<?php echo input('term')?>" type="text" class="form-control filter-input" data-name="term" placeholder="<?php _lang('group::find-groups')?>"/>
                    <button class="btn btn-info"><i class="ion-search"></i></button>
                </form>
            </div>
        </div>
        <div class="  filter-pane">
            <select id="video-filter-select" onchange="return run_global_filter()" data-name="filter" class="c-select filter-input">
                <option value="all"><?php _lang('all')?></option>
                <option <?php echo (input('filter') == 'top') ? 'selected' : null?> value="top"><?php _lang('top')?></option>
                <option <?php echo (input('filter') == 'featured') ? 'selected' : null?> value="featured"><?php _lang('featured')?></option>
            </select>
            <div class="list-layout-type">
                <a href="" onclick="return change_listing_layout('#group-list-container', 'list', 'group_set_list_type')"><i class="ion-ios-list-outline"></i></a>
                <a href="" onclick="return change_listing_layout('#group-list-container', 'grid', 'group_set_list_type')"><i class="ion-android-apps"></i></a>
            </div>
        </div>
    </div>
    <div id="group-list-container" class="box-content clearfix <?php echo ($list_type == 'list') ? 'list-listing-container' : 'grid-listing-container' ?>">
        <?php foreach($groups->results() as $group):?>
            <?php echo view('group::display', array('group' => $group))?>
        <?php endforeach?>
    </div>
    <div class="box-content">
        <?php if(!$groups->total):?>
            <?php _lang('group::no-grouo-found')?>
        <?php else:?>
            <?php echo $groups->append(array('term' => input('term'), 'type' => input('type', 'recommend'), 'filter' => input('filter')))->links(true)?>
        <?php endif?>
    </div>
</div>