<div class="box">
    <div class="title"><?php _lang('privacy-settings')?></div>
    <div class="box-content" style="padding:30px 10%">
        <form action="" method="post">
			<?php CSRFProtection::embed() ?>
            <div class="row form-group">
                <div class="col-md-5">
                    <h6><?php _lang('who-can-see-profile')?></h6>

                </div>
                <div class="col-md-7" >
                   <select class="c-select" name="val[who_can_view_profile]">
                       <option <?php echo (get_privacy('who_can_view_profile', config('default-profile-privacy', 1)) == '1') ? 'selected' : null?> value="1" ><?php _lang('everyone')?></option>
                       <option <?php echo (get_privacy('who_can_view_profile', config('default-profile-privacy', 1)) == '2') ? 'selected' : null?> value="2"><?php echo (config('relationship-method', 2) == 2 or config('relationship-method', 2) == 3) ? lang('friends-only') : lang('followers-only')?></option>
                       <option <?php echo (get_privacy('who_can_view_profile', config('default-profile-privacy', 1)) == '3') ? 'selected' : null?> value="3"><?php _lang('only-me')?></option>
                   </select>
                    <p class="text-muted"><?php _lang('who-can-see-profile-desc')?></p>
                </div>
            </div>

            <div class="row form-group">
                <div class="col-md-5">
                    <h6><?php _lang('who-can-post-profile')?></h6>

                </div>
                <div class="col-md-7" >
                    <select class="c-select" name="val[who_can_post_profile]">
                        <option <?php echo (get_privacy('who_can_post_profile', 1) == '1') ? 'selected' : null?> value="1" ><?php _lang('everyone')?></option>
                        <option <?php echo (get_privacy('who_can_post_profile', 1) == '2') ? 'selected' : null?> value="2"><?php echo (config('relationship-method', 2) == 2 or config('relationship-method', 2) == 3) ? lang('friends-only') : lang('followers-only')?></option>
                        <option <?php echo (get_privacy('who_can_post_profile', 1) == '3') ? 'selected' : null?> value="3"><?php _lang('only-me')?></option>
                    </select>
                    <p class="text-muted"><?php _lang('who-can-post-profile-desc')?></p>
                </div>
            </div>
            <div class="divider"></div>
            <?php if(config('relationship-method') > 1):?>
                <div class="row form-group">
                    <div class="col-md-5">
                        <h6><?php _lang('turn-on-friend-requests')?></h6>

                    </div>
                    <div class="col-md-7" style="margin: 0">
                        <input type="hidden" name="" value="off"/>
                        <select name="val[turn_on_friend_requests]" class="c-select">
                            <option <?php echo (get_privacy('turn_on_friend_requests', '1') == '1') ? 'selected' : null?> value="1"><?php _lang('yes')?></option>
                            <option <?php echo (get_privacy('turn_on_friend_requests', '1') == '0') ? 'selected' : null?> value="0"><?php _lang('no')?></option>
                        </select>
                    </div>
                </div>

            <?php endif?>

            <div class="row form-group">
                <div class="col-md-5">
                    <h6><?php _lang('who-can-see-birthdate')?></h6>

                </div>
                <div class="col-md-7" >
                    <select class="c-select" name="val[who_can_see_birth]">
                        <option <?php echo (get_privacy('who_can_see_birth', config('default-birthdate-privacy', 1)) == '1') ? 'selected' : null?> value="1" ><?php _lang('everyone')?></option>
                        <option <?php echo (get_privacy('who_can_see_birth', config('default-birthdate-privacy', 1)) == '2') ? 'selected' : null?> value="2"><?php echo lang('friends-only') ?></option>
                        <option <?php echo (get_privacy('who_can_see_birth', config('default-birthdate-privacy', 1)) == '3') ? 'selected' : null?> value="3"><?php _lang('only-me')?></option>
                    </select>
                    <p class="text-muted"><?php _lang('who-can-see-birthdate-desc')?></p>
                </div>
            </div>
            <?php echo theme_extend('privacy-settings')?>

            <div class="divider"></div>

            <div class="row form-group">
                <div class="col-md-5">
                    <h6><?php _lang('email-notifications')?></h6>

                </div>
                <div class="col-md-7" >
                    <select class="c-select" name="val[email-notification]">
                        <option <?php echo (get_privacy('email-notification', config('email-notification', 1)) == '1') ? 'selected' : null?> value="1" ><?php _lang('yes')?></option>
                        <option <?php echo (get_privacy('email-notification', config('email-notification', 1)) == '0') ? 'selected' : null?> value="0"><?php _lang('no')?></option>

                    </select>

                </div>
            </div>

            <button class="btn btn-info"><?php _lang('save')?></button>
        </form>
    </div>
</div>