<div class="media <?php echo (isset($type)) ? $type : 'media-lg'?> user">
    <div class="media-left">
        <a ajax="true" href="<?php echo profile_url(null, $user)?>" class="media-object"><img class="responsive-img" src="<?php echo get_avatar(75, $user)?>"/> </a>
    </div>
    <div class="media-body">

        <a class="media-heading" style="font-weight:bold" ajax="true" href="<?php echo profile_url(null, $user)?>"><?php echo get_user_name($user)?> <?php echo verify_badge($user)?></a>
        <ul class="info">
            <li><i class="ion-android-people"></i> <?php echo count(get_friends($user['id']))?> <?php _lang('friends')?></li>
            <?php if(is_loggedIn() and $user['id'] != get_userid()):?>
                <?php $count = count(get_mutual_friends($user['id']))?>
                <?php if($count > 0) :?>
                    <li><i class="ion-android-person-add"></i> <?php echo $count?> <?php _lang('mutual-friends')?></li>
                <?php endif?>

            <?php endif?>
            <?php if($user['country']):?>
                <li><i class="ion-ios-location"></i> <?php echo ucwords($user['country'])?></li>
            <?php endif?>
        </ul>
        <div class="action">
            <?php if(plugin_loaded('relationship')):?>
                <?php echo view('relationship::button', array('userid' => $user['id']))?>
            <?php endif?>
        </div>
    </div>
</div>
