<?php
$order = input('o') ? input('o') : null;
$current_class = array('l' => '', 'n' => '', 't' => '', 'f' => '');
switch($order){case 'l': $current_class['l'] = ' active';break;case 't':$current_class['t'] = ' active';break;case 'f':$current_class['f'] = ' active';break;default:$current_class['n'] = ' active';break;}
$url = http_build_query($_GET) == '' ? url_to_pager("forum-slug", array('appends' => '')) : url_to_pager("forum-slug", array('appends' => '')).'?'.http_build_query($_GET);
?>
<div class="box">
    <div class="box-content">
        <a class="btn btn-primary btn-block" href="<?php echo url_to_pager('forum-create-thread') ?>" ajax="true"><?php echo lang('forum::new-topic') ?></a>
    </div>
    <ul class="menu">
        <?php foreach(get_menus("forum-menu") as $menu):?>
            <li><a <?php echo ($menu->ajax) ? 'ajax="true"' : null?> <?php echo ($menu->tab) ? 'onclick="return window.open(\''.$menu->link.'\')"' : null?>  href="<?php echo ($menu->tab) ? 'javascript:void(0)' : $menu->link?>"><?php echo _lang($menu->title)?></a> </li>
        <?php endforeach?>
        <li class="<?php echo $current_class['l'] ?>"><a href="<?php echo forum_get_forum_slug_link(forum_assign_get_var(forum_remove_get_var($url, 's'), 'o', 'l')) ?>" title="<?php echo lang('forum::latest-desc') ?>" ajax="true"><?php echo lang('forum::latest') ?></a></li>
        <li class="<?php echo $current_class['n'] ?>"><a href="<?php echo forum_get_forum_slug_link(forum_assign_get_var(forum_remove_get_var($url, 's'), 'o', 'n')) ?>" title="<?php echo lang('forum::new-desc') ?>" ajax="true"><?php echo lang('forum::new') ?></a></li>
        <li class="<?php echo $current_class['t'] ?>"><a href="<?php echo forum_get_forum_slug_link(forum_assign_get_var(forum_remove_get_var($url, 's'), 'o', 't')) ?>" title="<?php echo lang('forum::top-desc') ?>" ajax="true"><?php echo lang('forum::top') ?></a></li>
        <?php if(is_loggedIn()): ?>
        <li class="<?php echo $current_class['f'] ?>"><a href="<?php echo forum_get_forum_slug_link(forum_assign_get_var(forum_remove_get_var($url, 's'), 'o', 'f')) ?>" title="<?php echo lang('forum::followed-desc') ?>" ajax="true"><?php echo lang('forum::followed').forum_followed_count() ?></a></li>
        <?php endif ?>
    </ul>
</div>