<div class="panel-container card register-pane-container" >
    <div class="title"><?php _lang('signup-for-account')?></div>
    <div class="card-block">


        <?php if($message):?>
            <div class="alert alert-danger">
                <?php echo $message?>
            </div>
        <?php endif?>


        <form action="<?php echo url_to_pager('signup')?>"   method="post">
            <?php CSRFProtection::embed()?>
            <div class="form-group">
                <div class="row" >
                    <div class="col-md-6">
                        <input class="form-control form-control-lg" value="<?php echo input('val.first_name')?>" type="text" name="val[first_name]" placeholder="<?php _lang('your-first-name')?>"/>
                    </div>
                    <div class="col-md-6">
                        <input class="form-control form-control-lg" value="<?php echo input('val.last_name')?>" type="text" name="val[last_name]" placeholder="<?php _lang('your-last-name')?>"/>
                    </div>
                </div>
            </div>

            <div class="form-group" >
                <input  class="form-control form-control-lg " value="<?php echo input('val.username')?>" type="text" name="val[username]" placeholder="<?php _lang('choose-username')?>"/>
            </div>

            <div class="form-group">
                <input  class="form-control form-control-lg" value="<?php echo input('val.email_address')?>" type="text" name="val[email_address]" placeholder="<?php _lang('your-email-address')?>"/>
            </div>
            <div class="form-group">
                <input  class="form-control form-control-lg" value="<?php echo input('val.password')?>" type="password" name="val[password]" placeholder="<?php _lang('choose-password')?>"/>
            </div>

            <div class="form-group">
                <input  class="form-control form-control-lg" value="<?php echo input('val.cpassword')?>" type="password" name="val[cpassword]" placeholder="<?php _lang('confirm-password')?>"/>
            </div>

            <div class="form-group">
                <select class=" form-control" name="val[country]">
                    <option value=""><?php _lang('select-country')?></option>
                    <?php foreach(get_countries() as $country => $name):?>
                        <option <?php echo (input("val.country") == $name) ? "selected" : null?> value="<?php echo $name?>"><?php echo ucwords($name)?></option>
                    <?php endforeach?>
                </select>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <label><?php _lang('gender')?></label>
                    <select class=" form-control" name="val[gender]">
                        <option <?php echo (input("val.gender") == "male") ? "selected" : null?> value="male"><?php _lang('male')?></option>
                        <option <?php echo (input("val.gender") == "female") ? "selected" : null?> value="female"><?php _lang('female')?></option>
                    </select>
                </div>

                <div class="col-md-6">
                    <?php echo view('birthdate/form', array(
                        'day' => input('val.birth_day'),
                        'month' => input('val.birth_month'),
                        'year' => input('val.birth_year')))?>

                </div>

            </div>



            <?php foreach(get_form_custom_fields('user') as $field):?>
                <?php echo view("custom-field/display", array('field' => $field, 'offDescription' => true))?>
            <?php endforeach?>
            <?php echo fire_hook('signup.form.extend', null, array('')) ?>
            <?php if(get_setting("enable-captcha")):?>
                <?php if(get_setting("enable-captcha") == '1'):?>
                    <div class="row">
                        <div class="col-md-6">
                            <input class="form-control" type="text" placeholder="<?php _lang('enter-text-below')?>" name="captcha" id="captcha-input"/>
                        </div>
                        <div class="col s6">
                            <img id="captcha-image" src="<?php echo url("captcha.php")?>"/>
                            <a style="position: relative;bottom: 10px" href="javascript:void(0)" onclick="document.getElementById('captcha-image').src='<?php echo url('captcha.php')?>?'+Math.random();
                                document.getElementById('captcha-input').focus();
                                "><i class="ion-ios-reload"></i></a><br/>
                        </div>
                    </div>

                <?php else:?>
                    <div class="g-recaptcha" data-sitekey="<?php echo config('recaptcha-key'); ?>"></div>
                    <script type="text/javascript"
                            src="https://www.google.com/recaptcha/api.js?hl=en">
                    </script>
                <?php endif?>
            <?php endif?>

            <div  class="" style="text-align: center">
                <button style="margin-top: 40px" class="btn btn-info"><?php _lang('signup')?> </button>
            </div>

        </form>

    </div>

</div>
