<div class="wrapper">
    <div class="wrapper-title"><?php _lang('game::manage-categories')?> <a href="<?php echo url_to_pager('admin-game-category-add')?>"><?php _lang('game::add-category')?></a> </div>
    <div class="wrapper-content">
        <table  class="table table-bordered ">
            <thead>
            <tr>
                <th style="width: 10%">ID</th>
                <th style="width: 30%"><?php _lang('game::category-title')?></th>
                <th style="width: 40%"><?php _lang('game::category-cover-image')?></th>
                <th style="width: 20%"><?php _lang('actions')?></th>
            </tr>
            </thead>
            <tbody data-url="<?php echo url_to_pager('admin-game-manage-category').'?action=order'?>" class="admincp-sortable" style="position: relative">
            <?php foreach($categories as $category):?>
                <tr style="" class="item" id="<?php echo $category['id']?>">
                    <td style="width: 10%"><?php echo $category['id']?></td>
                    <td style="width: 30%"><?php _lang($category['title']) ?></td>
                    <td style="width: 40%">
                        <?php if($category['cover']):?>
                            <img src="<?php echo  url_img($category['cover'])?>" style="width: 300px"/>
                        <?php else:?>
                            <?php _lang('nill')?>
                        <?php endif?>
                    </td>
                    <td style="width: 20%">
                        <a class="btn btn-sm btn-success" href="<?php echo url_to_pager('admin-game-manage-category').'?action=edit&id='.$category['id']?>"><?php _lang('edit')?></a>
                        <a class="btn btn-sm btn-danger admin-confirm" href="<?php echo url_to_pager('admin-game-manage-category').'?action=delete&id='.$category['id']?>"><i class="ion-android-delete"></i></a>
                    </td>
                </tr>
            <?php endforeach?>
            </tbody>
        </table>
    </div>
</div>