<?php $groups = get_groups('recommend', null, $limit, 'featured')?>

<?php if(is_loggedIn() and $groups->total):?>

    <div class="box">
        <div class="title"><?php _lang('group::featured-groups')?></div>
        <div class="box-content">
            <?php foreach($groups->results() as $group):?>
                <div class="media media-md"  style="padding: 5px">
                    <div class="media-left">
                        <a href="<?php echo group_url(null, $group)?>" ajax="true">
                            <div class="media-object"><img src="<?php echo get_group_logo(75, $group)?>"/> </div>
                        </a>
                    </div>
                    <div class="media-body">
                        <a href="<?php echo group_url(null, $group)?>" ajax="true"><h6 class="media-heading"><?php echo $group['group_title']?></h6></a>
                        <span><i class="ion-android-people"></i> </span> <strong><?php echo count(get_group_members_id($group['group_id']))?></strong> <?php _lang('group::members')?>

                    </div>
                </div>
            <?php endforeach?>

        </div>
    </div>
<?php endif?>