<div class="panel-container card">
    <div class="title"><?php echo lang('reset-password')?></div>
    <div class="card-block" >




        <?php if($message):?>
            <div class="alert alert-danger">
                <?php echo $message?><br/>

            </div>
        <?php endif?>
        <form action=""  class="col s12" method="post">
			<?php CSRFProtection::embed() ?>
            <fieldset class="form-group">
                <label for="exampleInputEmail1">Choose new password</label>
                <input name="val[password]" type="password" class="form-control form-control-lg" id="exampleInputEmail1" value="<?php echo input('val.password')?>">

            </fieldset>

            <fieldset class="form-group">
                <label for="InputConfirmPassword">Confirm new password</label>
                <input name="val[confirm_password]" type="password" class="form-control form-control-lg" id="InputConfirmPassword" value="<?php echo input('val.password')?>">

            </fieldset>


            <button  class="btn btn-block btn-info">Reset Password </button>

        </form>


    </div>


</div>
