<div  id="feed-lists" data-type="saved" data-type-id="" data-offset="0">
    <?php $i = 0; foreach($feeds as $feed):fire_hook('feed.lists.inline', null, array($i));$i++?>
        <?php echo view('feed::feed', array('feed' => $feed))?>
    <?php endforeach?>


</div>

<?php if(count($feeds)):?>
    <div class="feed-load-more">
        <div class="col-sm-2 no-padding"></div>
        <div class="col-sm-10 no-padding">
            <a href="" class="z-depth-1"><?php _lang('load-more')?></a>
            <img src="<?php echo img('images/loading.gif')?>" class=""/>
        </div>
    </div>
<?php else:?>
    <div class="box">
        <div class="box-content">
            <div class="alert alert-danger"><?php _lang('no-saved-post')?></div>
        </div>
    </div>
<?php endif?>