<?php echo view('layouts/menu')?>

<div class="container">
    <div data-width="950" class="profile-container" id="group-profile-container" data-id="<?php echo get_group_details('group_id')?>">
        <div id="profile-cover" class="box">
            <div class="profile-cover-indicator">
                <img src="<?php echo img('images/loading.gif')?>"/>
            </div>
            <div class="profile-cover-wrapper">

                <img src="<?php echo get_group_cover(app()->profileGroup, false)?>"/>
            </div>
            <?php if(is_group_admin($app->profileGroup)):?>

                <div class="profile-resize-cover-wrapper">
                    <div class="drag-info"><?php _lang('drag-to-position-cover')?></div>
                    <img src="<?php echo get_group_cover(app()->profileGroup)?>"/>
                </div>
                <form id="profile-cover-change-form" enctype="multipart/form-data" method="post">
					<?php CSRFProtection::embed() ?>
                    <span class="file-input"><input accept="image/*" multiple onchange="return upload_group_profile_cover()" type="file" id="user-profile-cover-input" name="image"/> </span>
                    <button   class="btn btn-sm btn-secondary dropdown-toggle" data-toggle="dropdown"><i class="ion-camera"></i> <?php _lang('change-cover')?></button>
                    <ul style="width: 240px" class="dropdown-menu dropdown-menu-right" id="profile-cover-dropdown-menu">
                        <li><a class="dropdown-item" onclick="return file_chooser('#user-profile-cover-input')" href=""><?php _lang('upload-photo')?>...</a> </li>
                        <li class="hide-in-mobile"><a class="dropdown-item" onclick="return reposition_user_profile_cover()" href=""><?php _lang('reposition')?>...</a> </li>
                        <li><a class="dropdown-item" onclick="return remove_group_profile_cover('<?php echo img("images/cover.jpg")?>')" href=""><?php _lang('remove')?>...</a> </li>
                    </ul>
                </form>
                <div class="profile-cover-reposition-button">
                    <input type="hidden" id="profile-cover-resized-top" value="0"/>
                    <a onclick="return cancel_profile_cover_position()" class="btn-danger-outline btn btn-sm" href="#!"><?php _lang('cancel')?></a>
                    <a onclick="return save_group_profile_cover()" class="btn btn-success btn-upper btn-sm" href=""><?php _lang('save')?></a>
                </div>
            <?php endif?>
            <div class="user-avatar box">
                <?php if(is_group_admin($app->profileGroup)):?>
                    <form data-id="<?php echo $app->profileGroup['group_id']?>" id="group-profile-image-form" action="" method="post" enctype="multipart/form-data">
						<?php CSRFProtection::embed() ?>
						<span class="file-input"><input accept="image/*" multiple onchange="upload_group_logo()" type="file" id="page-avatar-input" name="logo"/> </span>
                        <a class="profile-image-selector" id="profile-image-selector" href="" onclick="return file_chooser('#page-avatar-input')"><i class="ion-ios-camera"></i> <span></span></a>
                    </form>
                <?php endif?>
                <div class="profile-image-indicator">
                    <img src="<?php echo img("images/loading.gif")?>"/>
                    <span class="percent-indicator">0%</span>
                </div>

                <img class="profile-image"  src="<?php echo get_group_logo(200, app()->profileGroup)?>"/>
            </div>
            <div class="user-info">
                <h4 class="user-name left"><?php echo get_group_details('group_title')?></h4>
            </div>

            <nav id="profile-menu" class="">
                <div class="navbar navbar-light">
                    <ul id="menu" class="nav navbar-nav">
                    <?php foreach(get_menus("group-profile") as $menu):?>
                        <li class="<?php echo ($menu->isActive() == 1) ? 'active' : null?>"><a ajax="true" href="<?php echo $menu->link?>"><?php echo $menu->title?></a></li>
                    <?php endforeach?>

                    </ul>

                </div>
            </nav>
        </div>

        <div class="profile-actions">
            <span class="group-social-share"><?php if(plugin_loaded('sharer')) echo view('sharer::share_link', array('link' => url($app->profileGroup['group_name']))) ?></span>
            <?php if(is_loggedIn() and !is_group_admin($app->profileGroup, null, false)):?>
                <?php $status = (is_group_member($app->profileGroup['group_id'])) ? 1 : 0?>
                <a onclick="return join_group(this)" data-id="<?php echo $app->profileGroup['group_id']?>" class="btn btn-info" data-status="<?php echo $status?>" data-join="<?php echo lang('group::join-group')?>" data-leave="<?php echo lang('group::leave-group')?>" href="">
                    <?php echo ($status)  ? lang('group::leave-group') : lang('group::join-group')?>
                </a>
            <?php endif?>

            <?php if(is_loggedIn() and is_group_admin($app->profileGroup)):?>
                <a href="<?php echo group_url('edit')?>" ajax="true" class="btn btn-secondary"><i class="ion-edit"></i> <?php _lang('edit')?></a>
            <?php endif?>

            <?php if(is_loggedIn() and plugin_loaded('report')):?>
                <a  data-type="group" data-link="<?php echo group_url(null, $app->profileGroup)?>" class="report-btn btn btn-secondary " href=""><i class="ion-flag"></i></a>
            <?php endif?>

            <?php if(is_loggedIn()):?>
                <span class="dropdown">
                        <a  href="" class="dropdown-toggle btn btn-secondary" data-toggle="dropdown" style=""><i class="ion-android-more-vertical"></i></a>
                        <ul class="dropdown-menu dropdown-menu-right">
                            <li>
                                <a onclick="return process_user_save(this, 'group', '<?php echo $app->profileGroup['group_id']?>')" href="" class="dropdown-item user-save" data-status="<?php echo (user_saved('group', $app->profileGroup['group_id'])) ? 1 : 0?>">
                                    <i class="ion-android-bookmark"></i>
                                    <span><?php echo (user_saved('group', $app->profileGroup['group_id'])) ? lang('unsave-post') : lang('save-post')?></span>
                                </a>
                            </li>
                        </ul>
                    </span>

            <?php endif?>
        </div>
    </div>

</div>
<?php echo $content?>