<?php if(group_can_post()):?>
    <?php echo view('feed::editor', array(
            'offPrivacy' => true,
            'privacy' => 4,
            'type' => 'group',
            'type_id' => $app->profileGroup['group_id'],
            'offTagging' => true
        )
    )?>
<?php endif?>

<div  id="feed-lists" data-type="group" data-type-id="<?php echo $app->profileGroup['group_id']?>" data-offset="0">
    <?php $feed = get_pinned_feed('group', $app->profileGroup['group_id']); if ($feed) echo view('feed::feed', array('feed' => $feed))?>
    <?php $i = 0; foreach($feeds as $feed):fire_hook('feed.lists.inline', null, array($i));$i++?>
        <?php echo view('feed::feed', array('feed' => $feed))?>
    <?php endforeach?>


</div>
<?php if(!count($feeds)):?>
    <div class="feed-empty text-center">
        <i class="ion-android-bicycle"></i>
        <h3><?php _lang('no-post-show')?></h3>
    </div>
<?php endif?>
<?php if(count($feeds)):?>
    <div class="feed-load-more">
        <div class="col-sm-2 no-padding"></div>
        <div class="col-sm-10 no-padding">
            <a href="" class="z-depth-1"><?php _lang('load-more')?></a>
            <img src="<?php echo img('images/loading.gif')?>" class=""/>
        </div>
    </div>
<?php endif?>

