<div class="row">
    <div class="col-md-4 left-column">
        <?php echo view('page::manage/menu')?>
    </div>
    <div class="col-md-8 right-column">
        <div class="box">
            <div class="title"><?php _lang('page::page-information')?></div>
            <div class="box-content">
                <?php if($message):?>
                    <div class="alert alert-success"><?php echo $message?></div>
                <?php endif?>
                <form action="" method="post">
					<?php CSRFProtection::embed() ?>
                    <div class="form-group row">
                        <div class="col-sm-12">
                            <?php foreach($fields as $field):?>
                                <?php echo view("custom-field/display", array('field' => $field, 'value' => get_page_details($field['title'])))?>
                            <?php endforeach?>
                        </div>
                    </div>

                    <button class="btn btn-info"><?php _lang('save')?></button>
                </form>
            </div>
        </div>
    </div>
</div>