<div class="row">
    <div class="col-md-4 left-column">
        <?php echo view('page::manage/menu')?>
    </div>
    <div class="col-md-8 right-column">
        <div class="box">
            <div class="title"><?php _lang('page::general-settings')?></div>
            <div class="box-content">
                <?php if($message):?>
                    <div class="alert alert-success"><?php echo $message?></div>
                <?php endif?>
                <form action="" method="post">
					<?php CSRFProtection::embed() ?>
                    <div class="form-group row">
                        <label class="control-label col-sm-4"><?php _lang('page::select-category')?></label>
                        <div class="col-sm-8">
                            <select name="val[category]" class="c-select">
                                <?php foreach(get_page_categories() as $category):?>
                                    <option <?php echo ($app->profilePage['page_category_id'] == $category['category_id']) ? 'selected' : null?> value="<?php echo $category['category_id']?>"><?php _lang($category['category_title'])?></option>
                                <?php endforeach?>
                            </select>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="control-label col-sm-4"><?php _lang('page-title')?></label>
                        <div class="col-sm-8">
                            <input value="<?php echo $app->profilePage['page_title']?>" type="text" name="val[name]" class="form-control"/>
                        </div>
                    </div>

                    <?php if(config('request-verification', true)):?>
                        <div style="margin: 20px 0">
                            <?php if(get_user_data('verified')):?>
                                <button type="button" class="btn btn-success btn-block disabled"><i class="ion-checkmark-circled"></i> <?php _lang('verified')?></button>
                            <?php else:?>
                                <?php if(verify_requested('page', $app->profilePage['page_id'])):?>
                                    <button type="button" class="btn btn-danger btn-block disabled"><i class="ion-checkmark-circled"></i> <?php _lang('verify-requested')?></button>
                                <?php else:?>
                                    <a class="btn btn-secondary btn-block" href="<?php echo url('user/verify/request?type=page&id='.$app->profilePage['page_id'])?>"> <i class="ion-checkmark-circled"></i> <?php _lang('request-verification')?></a>
                                <?php endif?>
                            <?php endif?>
                        </div>
                    <?php endif?>

                    <div class="form-group row">
                        <label class="control-label col-sm-4"><?php _lang('page::page-description')?></label>
                        <div class="col-sm-8">
                            <textarea name="val[description]" class="form-control auto-grow"><?php echo $app->profilePage['page_desc']?></textarea>
                        </div>
                    </div>

                    <button class="btn btn-info"><?php _lang('save')?></button>
                </form>
            </div>
        </div>
    </div>
</div>