

<ul id="profile-side-info">

    <?php foreach(get_custom_fields('page', $id) as $field):?>
        <?php if(get_page_details($field['title'], $app->profilePage)):?>
            <li>
                <span><i class="ion-ios-information-outline"></i> <?php _lang($field['title'])?>:</span> <?php echo output_text(get_page_details($field['title'], $app->profilePage))?>
            </li>
        <?php endif?>
    <?php endforeach?>
</ul>