<?php $listings = marketplace_get_listings(null, null, null, 1, $limit); ?>
<?php if(count($listings->results()) > 0): ?>
<div class="marketplace box listings-box">
    <div class="title"><?php echo lang('marketplace::latest-listings')?> <a ajax="true" href="<?php echo url_to_pager('marketplace', array('appends' => ''))?>" class="more-link pull-right"><i class="ion-ios-arrow-forward"></i></a></div>
    <div class="clearfix">
        <?php foreach($listings->results() as $listing): ?>
            <?php if($listing['image']): ?>
                <?php $listing_image = url_img($listing['image'], 200); ?>
            <?php else: ?>
                <?php $listing_image = img('marketplace::images/no_image.jpg'); ?>
            <?php endif ?>
            <a  href="<?php echo url_to_pager('marketplace-listing-slug', array('appends' =>marketplace_get_slug($listing['id'], 'listing'))) ?>" ajax="true" class="listing " style="background-image: url(<?php echo $listing_image ?>)">
                <h6 class="name"><?php echo $listing['title'] ?></h6>
            </a>
        <?php endforeach?>
    </div>
</div>
<?php endif ?>