<div class="contact box">
    <div class="title"><?php echo lang('contact::contact-form-message')?></div>
    <form action="" method="post">
        <?php if($message): ?><div class="alert alert-success"><?php echo $message ?></div><?php endif ?>
        <?php echo CSRFProtection::embed() ?>
        <div class="box-content">
            <div class="row">
                <div class="col-sm-4"><label><?php echo lang('contact::name') ?></label></div>
                <div class="col-sm-8"><input name='val[name]' type="text" required="" class="form-control"></div>
                <div class="col-sm-4"><label><?php echo lang('contact::email') ?>:</label></div>
                <div class="col-sm-8"><input name='val[email]' type="email" required="" class="form-control"></div>
                <div class="col-sm-4"><label><?php echo lang('contact::subject') ?>:</label></div>
                <div class="col-sm-8"><input name='val[subject]' type="text" required="" class="form-control"></div>
                <div class="col-sm-4"><label><?php echo lang('contact::message') ?>:</label></div>
                <div class="col-sm-8"><textarea name='val[message]' required="" class="form-control ckeditor"></textarea></div>
                <div class="col-sm-4"></div>
                <div class="col-sm-8"><button type="submit" name="reply" class="btn btn-info"><?php echo lang('contact::send') ?> </button></div>
            </div>
        </div>
    </form>
</div>