<?php echo view('installer/header', array('title' => 'Database Details'))?>
    <div class="container">
        <div class="title">Database Details</div>
        <div class="content">
            <?php if($message):?>
                <div class="alert alert-error"><?php echo $message?></div>
            <?php endif?>

            <form action="" method="post">
            <?php CSRFProtection::embed() ?>
                <label>Database Hostname:</label>
                <input value="<?php echo installer_input('val.host')?>" type="text" name="val[host]" placeholder="Database hostname"/>

                <label>Database Username:</label>
                <input value="<?php echo installer_input('val.username')?>" type="text" name="val[username]" placeholder="Database Username"/>

                <label>Database Name:</label>
                <input value="<?php echo installer_input('val.name')?>" type="text" name="val[name]" placeholder="Database name"/>

                <label>Database Password:</label>
                <input value="<?php echo installer_input('val.password')?>" type="text" name="val[password]" placeholder="Database password"/>

                <div class="footer">
                    <div class="buttons">
                        <button class="btn">Save and Install Database</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
<?php echo view('installer/footer')?>