<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>crea8socialPRO - <?php echo $title?></title>
    <link media="all" type="text/css" rel="stylesheet" href="<?php echo url("installer/assets/normalize.css")?>">
    <link media="all" type="text/css" rel="stylesheet" href="<?php echo url("installer/assets/style.css")?>">
    <script src="<?php echo url('installer/assets/script.js')?>"></script>

<div class="header">
        crea8socialPRO Installation
    </div>