<?php if(count($users) > 0 ):?>
    <?php foreach($users as $user):?>
	<?php $canStream = plugin_loaded('mediachat') && mediachat_can_user_stream($user['id']) ? 'true' : 'false'; ?>
        <a onclick="return Chat.open(null, '<?php echo $user['id']?>', '<?php echo htmlentities(get_user_name($user)) ?>', '<?php echo get_avatar(75, $user)?>', null, null, <?php echo $canStream ?>)" href="">

            <div class="media media-sm">
                <div class="media-left">
                    <div class="media-object"><img src="<?php echo get_avatar(75, $user)?>"/> </div>
                </div>
                <div class="media-body">
                    <h6 class="media-heading"><?php echo get_user_name($user)?></h6>
                    <?php if($user['online_time'] < time() - 50):?>
                        <span class="action"><?php echo timeAgoMin($user['online_time'])?></span>
                    <?php else:?>
                        <span class="online-status <?php echo get_online_status_icon($user) ?>"></span>
                    <?php endif?>

                </div>
            </div>
        </a>
    <?php endforeach?>
<?php else:?>
<div style="padding: 10px"><?php _lang('chat::no-friends-online')?></div>
<?php endif?>