<div class="wrapper">
    <div class="wrapper-title">
        <?php _lang("page::add-category")?>
    </div>
    <div class="wrapper-content">
        <form method="post" action="" class="wrapper-form">
			<?php CSRFProtection::embed() ?>
            <div class="form-group row">
                <label class="col-sm-3 form-control-label"><?php _lang('page::category-title')?></label>
                <div class="col-sm-9">
                    <?php foreach(get_all_languages() as $language):?>
                        <input class="form-control" type="text" name="val[title][<?php echo $language['language_id']?>]" placeholder="<?php _lang('page::category-title')?>"/><br>
                        <p class="help-block"><?php echo $language['language_title']?></p>
                    <?php endforeach?>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-sm-3 form-control-label"><?php _lang('page::category-desc')?></label>
                <div class="col-sm-9">

                    <?php foreach(get_all_languages() as $language):?>
                        <textarea name="val[desc][<?php echo $language['language_id']?>]" class="form-control" placeholder="<?php _lang('page::category-desc')?>"></textarea>
                        <p class="help-block"><?php echo $language['language_title']?></p>
                    <?php endforeach?>
                </div>
            </div>

            <button class="btn btn-info"><?php _lang('page::add-category')?></button>
        </form>
    </div>
</div>