<div class="wrapper">
    <div class="wrapper-title"><?php echo lang('music::playlists-manager') ?></div>
    <div class="wrapper-content">
        <form action="" method="get" class="form-inline" style="margin: 20px 0">
			<?php CSRFProtection::embed() ?>
            <select class="c-select" name="limit">
                <option value="10">10 Per Page</option>
                <option value="20">20 Per Page</option>
                <option value="50">50 Per Page</option>
                <option value="100">100 Per Page</option>
                <option value="150">150 Per Page</option>
                <option value="200">200 Per Page</option>
            </select>
            <input type="hidden" class="music-type-input" value="<?php echo input('type','browse') ?>"/>
            <input name="term" value="<?php echo input('term') ?>" type="text" class="form-control" placeholder="<?php echo lang('music::search-playlists') ?>"/>
            <button class="btn btn-info"><?php echo lang('go') ?></button>
        </form>
        <table class="table table-borderd">
            <thead>
                <tr>
                    <th style="width:5%">ID</th>
                    <th style="width:25%"><?php echo lang('title') ?></th>
                    <th style="width:20%"><?php echo lang('owner') ?></th>
                    <th style="width:10%"><?php echo lang('featured') ?></th>
                    <th style="width:10%"><?php echo lang('music::play-count') ?></th>
                    <th style="widows: 20;%"><?php echo lang('actions') ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($playlists->results() as $playlist): ?>
                    <tr>
                        <td><?php echo $playlist['id'] ?></td>
                        <td><a href="<?php echo get_playlist_url($playlist) ?>"><?php echo $playlist['title'] ?></a> </td>
                        <td>
                            <?php $owner = get_playlist_owner($playlist) ?>
                            <a href="<?php echo $owner['link'] ?>"><?php echo $owner['name'] ?></a>
                        </td>
                        <td>
                            <?php echo ($playlist['featured']) ? lang('yes') : lang('no') ?>
                        </td>
                        <td><?php echo $playlist['play_count'] ?></td>
                        <td>
                            <a href="<?php echo url_to_pager('admin-playlist-manage-pager').'?action=edit&id='.$playlist['id'] ?>" class="btn btn-success"><i class="ion-edit"></i></a>
                            <a href="<?php echo url_to_pager('admin-playlist-manage-pager').'?action=delete&id='.$playlist['id'] ?>" class="btn btn-danger admin-confirm"><i class="ion-ios-close-empty"></i></a>
                        </td>
                    </tr>
                <?php endforeach ?>
            </tbody>
        </table>
        <?php echo $playlists->links() ?>
    </div>
</div>