<?php
$default = user_privacy("feed-editor-privacy", 1);
$privacy = (isset($privacy)) ? $privacy : $default;
$avatar = (isset($avatar)) ? $avatar : get_avatar(75);

?>
<div id="feed-editor" class="">
    <div class="col-sm-2 left no-padding">
        <div id="avatar" class="b">
            <img class="res-img" src="<?php echo $avatar?>"/>
        </div>
    </div>
    <div class="col-sm-10 right no-padding" style="">
    <div class="line"></div>
        <div class="" style="margin: 0">
            <div class="box" style="margin: 0;margin-bottom: 10px">
                <div id="post-editor-indicator">
                    <img src="<?php echo img('images/loading.gif')?>"/>
                    <span id="feed-media-upload-indicator">0%</span>
                </div>
                <div data-error="<?php echo lang('feed::feed-default-error')?>" style="" class="alert alert-danger" id="feed-editor-error">
                </div>
                <form style="margin: 0;padding: 0" id="feed-editor-form" action="" method="post">
                    <?php CSRFProtection::embed()?>
                    <input type="hidden" name="val[privacy]" value="<?php echo $privacy?>" id="feed-editor-privacy"/>
                    <input type="hidden" name="val[type]" value="<?php echo (isset($type)) ? $type : 'feed'?>"/>
                    <input type="hidden" name="val[type_id]" value="<?php echo (isset($type_id)) ? $type_id : ''?>"/>
                    <input type="hidden" name="val[type_data]" value="<?php echo (isset($type_data)) ? $type_data : ''?>"/>
                    <input type="hidden" name="val[entity_id]" value="<?php echo (isset($entity_id)) ? $entity_id : get_userid()?>"/>
                    <input type="hidden" name="val[entity_type]" value="<?php echo (isset($entity_type)) ? $entity_type : 'user'?>"/>
                    <input type="hidden" name="val[to_user_id]" value="<?php echo (isset($to_user_id)) ? $to_user_id : null?>"/>


                    <div class="row" id="feed-editor-content-container">

                        <div id="feed-editor-content" >
                            <div  class="clearfix" style="">
                                <div class="left">
                                    <textarea id="feed-editor-textarea" data-height="40px" data-mention="#feed-editor-mention" class="auto-grow-input mention-input <?php echo (config('enable-feed-text-limit', false)) ? 'textarea-limit' : null?>" data-text-limit="<?php echo config('maximum-feed-text-limit', 150)?>" data-text-limit-count-target="#feed-editor-text-limit"  name="val[content]" placeholder="<?php echo lang('feed::whats-happening')?>"></textarea>
                                    <div id="feed-editor-activity-container">
                                    </div>
                                </div>
                                <div class="right">
                                    <ul>
                                        <?php if(user_has_permission('can-upload-photo-feed')):?>
                                            <li>
                                                <span class="file-input"><input accept="image/*" multiple onchange="feedEditor.processMedia('image')" type="file" id="feed-editor-image-input" name="image[]"/> </span>
                                                <a id="feed-editor-image-selector" href="" onclick="return feedEditor.choose('#feed-editor-image-input', 'image')"><i class="ion-camera"></i> <span></span></a>
                                            </li>
                                        <?php endif?>
                                        <?php if(user_has_permission('can-upload-video-feed')):?>
                                            <li>
                                                <span class="file-input"><input <?php echo (plugin_loaded('video') and config('video-upload', false) and config('video-encoder') != 'none') ? '' : 'accept="video/mp4"' ?> onchange="feedEditor.processMedia('video')" type="file" id="feed-editor-video-input" name="video"/> </span>
                                                <a  id="feed-editor-video-selector" href="" onclick="return feedEditor.choose('#feed-editor-video-input', 'video')"><i class="ion-ios-videocam"></i> <span></span></a>
                                            </li>
                                        <?php endif?>

                                    </ul>
                                </div>

                            </div>
                            <div id="feed-editor-link-container">
                                <div class="link-indicator">
                                    <img src="<?php echo img('images/loading.gif')?>"/>
                                    <?php _lang('feed::retrieving-link-details')?>
                                </div>
                                <div class="link-content">

                                </div>
                            </div>
                            <div id="feed-editor-mention" class="mention-user-list box">
                                <img src="<?php echo img('images/loading.gif')?>" class="indicator"/>
                                <div class="listing user-suggestion-list"></div>
                            </div>
                            <div class="" id="feed-editor-check-in-input-container">
                                <i class="ion-ios-location"></i>
                                <input id="feed-geocomplete" autocomplete="off" type="text" name="val[location]" placeholder="<?php _lang('where-are-you')?>"/>
                                <a href="" onclick="return feedEditor.removeCheckIn()"><i class="ion-close"></i></a>
                            </div>

                            <div id="photo-feed-media-selected-info" class="feed-media-selected-info">
                                <i class="ion-camera"></i> <span class="count">0</span> <?php _lang('photos-selected')?>
                                <a class="remove" onclick="return feedEditor.removeImage()" href=""><i class="ion-close"></i></a>
                            </div>
                            <div id="video-feed-media-selected-info" class="feed-media-selected-info">
                                <i class="ion-ios-videocam"></i> <span class="count">0</span> <?php _lang('video-selected')?>
                                <a class="remove" onclick="return feedEditor.removeVideo()" href=""><i class="ion-close"></i></a>
                            </div>
                            <div id="file-feed-media-selected-info" class="feed-media-selected-info">
                                <i class="ion-document-text"></i> <span class="count">0</span> <?php _lang('files-selected')?>
                                <a class="remove" onclick="return feedEditor.removeFile()" href=""><i class="ion-close"></i></a>
                            </div>

                            <div id="feed-editor-tags-container">
                            <span style="display: none" class="" id="user-<?php echo get_userid()?>">

                            </span>
                            <span class="input-field">
                                <input data-friend-only="true" autocomplete="off" data-target="#feed-tags-suggestion" type="text" class="user-tag-input" placeholder="<?php _lang('tag-people-in-post')?>"/>
                                <div class="user-suggestion-list box" id="feed-tags-suggestion"></div>
                            </span>
                            </div>

                            <div class="feed-editor-feeling-container dropdown clearfix">
                                <div class="feeling-left">
                                    <?php $feelings = get_feelings_list();
                                        $firstFeeling = $feelings[0];
                                    ?>
                                    <a id="dropdown-link" href="" data-toggle="dropdown"><img src="<?php echo img("images/status/{$firstFeeling}.png")?>"/> <?php _lang("feed::{$firstFeeling}")?></a>
                                    <ul class="dropdown-menu">
                                        <?php foreach($feelings as $feeling):?>
                                            <li><a onclick="return feedEditor.loadFeeling(this)" href="" data-type="<?php echo $feeling?>" class="dropdown-item"><img src="<?php echo img("images/status/{$feeling}.png")?>"/> <?php _lang("feed::{$feeling}")?> <i class="ion-chevron-right pull-right"></i></a> </li>
                                        <?php endforeach?>
                                    </ul>
                                </div>
                                <div class="feeling-right">
                                    <input type="hidden" name="val[feeling_type]" id="feed-editor-feeling-type" value="<?php echo $firstFeeling?>">
                                    <input type="hidden" name="val[feeling_data]" id="feed-editor-feeling-data" value="">
                                    <input type="text" autocomplete="off" name="val[feeling_text]" onblur="return feedEditor.removeFeeling(this)" onkeyup="return feedEditor.listenMediaFeeling(this)" id="feed-editor-feeling-text"/>
                                    <div id="feed-feeling-selected-suggestion"></div>
                                    <div id="feed-feeling-suggestion">

                                    </div>
                                </div>
                            </div>

                            <div class="feed-editor-poll-container">
                                <input type="hidden" value="0" name="val[poll]" id="feed-poll-enable-input"/>
                                <div class="poll-options-container">
                                    <div class="options">
                                        <i class="ion-ios-plus-outline"></i> <input placeholder="<?php _lang('feed::option')?>" type="text" name="val[poll_options][]"/>
                                    </div>
                                    <div class="options">
                                        <i class="ion-ios-plus-outline"></i> <input placeholder="<?php _lang('feed::option')?>" type="text" name="val[poll_options][]"/>

                                    </div>

                                </div>
                                <a style="display:inline-block;" href="" onclick="return feedEditor.addOptions()"><i class="ion-ios-plus"></i> <?php _lang('feed::add-option')?></a>

                                <span class="">
                                    <label class="c-input c-checkbox">
                                        <input name="val[poll_multiple]" type="checkbox">
                                        <span class="c-indicator"></span>
                                        <?php _lang('feed::enable-multiple-section')?>
                                    </label>
                                </span>
                            </div>

                        </div>

                    </div>


                    <div class="feed-editor-footer row">
                        <ul class="menu pull-left">
                            <?php if(!isset($offTagging) and user_has_permission('can-tag-users-feed')):?>
                                <li id="feed-editor-tags-input-selector"><a onclick="return feedEditor.showTags()" data-toggle="tooltip" title="<?php lang('feed::tag-people-hint') ?>" href=""><i class="ion-ios-personadd-outline"></i></a> </li>
                            <?php endif?>
                            <li id="feed-editor-check-in-input-selector"><a data-toggle="tooltip" onclick="return feedEditor.toggleCheckIn()" title="<?php echo lang('feed::check-in') ?>" href=""><i class="ion-ios-location-outline"></i></a> </li>
                            <?php if(user_has_permission('can-share-file-feed')):?>
                                <li id="feed-editor-file-selector">
                                    <span class="file-input"><input  onchange="feedEditor.processMedia('file')" multiple type="file" id="feed-editor-file-input" name="file[]"/> </span>
                                    <a data-toggle="tooltip" onclick="return feedEditor.choose('#feed-editor-file-input', 'file')" title="<?php echo lang('feed::upload-a-file') ?>" href=""><i class="ion-android-cloud-outline"></i></a> </li>
                            <?php endif?>
                            <?php if(user_has_permission('can-use-feeling')):?>
                                <li>
                                    <a class="feed-feeling-trigger" href="" data-toggle="tooltip" ><i class="ion-android-happy"></i></a>
                                </li>
                            <?php endif?>
                            <?php if(config('enable-feed-poll', true) and user_has_permission('can-create-poll')):?>
                                <li>
                                    <a id="feed-editor-poll-toggle" data-revert="<?php echo lang('feed::whats-happening')?>" data-holder="<?php _lang('feed::ask-question')?>" onclick="return feedEditor.openPoll(this)" href="" data-toggle="tooltip" title="<?php _lang('feed::create-poll')?>" class=""><i class="ion-stats-bars"></i></a>
                                </li>.
                            <?php endif?>

                            <?php fire_hook('display.social.publisher',null,array()); ?>

                        </ul>

                        <div class="right-buttons pull-right">
                            <?php if(config('enable-feed-text-limit', false)):?>
                                <span id="feed-editor-text-limit"><?php echo config('maximum-feed-text-limit', 150)?></span>
                            <?php endif?>

                            <div class="" style="position: relative;display: inline-block">
                                <div class="emoticon-box  pull-right" style="right: 0;top:20px"></div>
                                <a data-target="feed-editor-textarea" data-action="0"  title="<?php _lang('emoticons::add-emoticons')?>" class="emoticon-button" href="javascript::void(0)"><i class="ion-happy-outline emo-button"></i></a>

                            </div>
                            <div class=" dropdown" style="display: inline-block">
                                <?php if(!isset($offPrivacy) or (isset($offPrivacy) and !$offPrivacy)):?>
                                    <a  id="feed-editor-privacy-toggle"  href="" class="dropdown-toggle btn btn-secondary btn-sm" data-toggle="dropdown">
                                        <?php $editorPrivacy = user_privacy("feed-editor-privacy", config('default-feed-privacy', 1));?>
                                        <?php if($editorPrivacy == 1):?>
                                            <i class="ion-earth" data-toggle="tooltip" title="<?php _lang('public')?>"></i></span>
                                        <?php elseif($editorPrivacy == 2):?>
                                            <i class="ion-ios-people" data-toggle="tooltip" title="<?php echo (config('relationship-method', 3) == 1) ? lang('feed::followers-only') : lang('feed::friends-only')?>"></i>

                                        <?php else:?>
                                            <i class="ion-android-lock" data-toggle="tooltip" title="<?php echo lang('feed::only-me')?>"></i>
                                        <?php endif?>

                                    </a>
                                    <ul id='feed-privacy-dropdown' class='dropdown-menu dropdown-menu-right'>
                                        <li><a data-id="1" class="dropdown-item" href="javascript:void(0)"><i class="ion-android-globe"></i> <span><?php echo lang('public')?></span></a></li>
                                        <li><a data-id="2" class="dropdown-item" href="javascript:void(0)">
                                                <i class="ion-ios-people"></i>
                                                <span><?php echo (config('relationship-method', 3) == 1) ? lang('feed::followers-only') : lang('feed::friends-only')?></span>
                                            </a></li>
                                        <li><a data-id="3" class="dropdown-item" href="javascript:void(0)">
                                                <i class="ion-android-lock"></i>
                                                <span><?php echo lang('feed::only-me')?></span>
                                            </a> </li>
                                    </ul>
                                <?php endif?>
                            </div>
                            <button class="btn btn-info btn-sm btn-upper"><i class="ion-android-send"></i> <?php _lang('post')?></button>



                        </div>

                    </div>
            </div>

            </form>
        </div>
    </div>
</div>
