<div class="feed-content" id="feed-content-<?php echo $feed['feed_id']?>">
    <span class="content"><?php echo format_feed_content($feed['feed_content'])?></span>

</div>

<?php if($feed['feeling_data']):$feeling = $feed['feeling_data']?>
    <div class="feed-feeling-content clearfix">
        <div class="feeling-left">
            <img src="<?php echo img("images/status/{$feeling['type']}.png")?>"/>

        </div>
        <div class="feeling-right">
            <strong><?php _lang("feed::{$feeling['type']}")?></strong>
            <?php echo $feeling['text']?>
        </div>
    </div>
    <?php $data = perfectUnserialize($feeling['data'])?>
    <?php if($data):?>
        <div class="feed-feeling-media-content">
            <?php if ($feeling['type'] == 'listening-to'):?>
                <iframe style="max-width:100%;" width="100%" height="120" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=<?php echo $data['link']?>"></iframe>
            <?php elseif($feeling['type'] == 'watching' and !preg_match("#soundcloud#", $data['link'])):?>
                <iframe style="width: 100%;max-width:100%;height: 320px" allowfullscreen frameborder="no" src="<?php echo $data['link']?>"></iframe>
            <?php endif?>
        </div>
    <?php endif?>
<?php endif?>

<?php if(isset($feed['images'])):?>
    <div class="feed-images">
        <?php if (count($feed['images']) == 1):?>
            <div class="one-image">
                <?php $i = 1; foreach($feed['images'] as $id => $image):?>
                    <?php if($i == 1):?>
                        <a data-image="<?php echo url_img($image, 920)?>" data-id="<?php echo $id?>" class="photo-viewer"  href="" style="">
                            <img src="<?php echo url_img($image, 600)?>"/>
                        </a>
                    <?php endif?>
                    <?php $i++; endforeach?>
            </div>
        <?php elseif(count($feed['images']) == 2):?>
            <div class="two-images clearfix">
                <?php foreach($feed['images'] as $id => $image):?>
                    <div>
                        <a data-image="<?php echo url_img($image, 920)?>" data-id="<?php echo $id?>" class="photo-viewer"  href="" style="background-image: url(<?php echo url_img($image, 600)?>)"></a>
                    </div>
                <?php endforeach?>
            </div>
        <?php elseif(count($feed['images']) == 3):?>

            <div class="three-images clearfix">
                <div class="col-sm-7 left">
                    <?php $i = 1; foreach($feed['images'] as $id => $image):?>
                        <?php if($i == 1):?>
                            <a data-image="<?php echo url_img($image, 920)?>" data-id="<?php echo $id?>" class="photo-viewer"  href="" style="background-image: url(<?php echo url_img($image, 600)?>)"></a>
                        <?php else: break;endif?>
                        <?php $i++; endforeach?>

                </div>
                <div class="col-sm-5 right">
                    <?php $i = 1; foreach($feed['images'] as $id => $image):?>
                        <?php if($i > 1):?>
                            <div>
                                <a data-image="<?php echo url_img($image, 920)?>" data-id="<?php echo $id?>" class="photo-viewer"  href="" style="background-image: url(<?php echo url_img($image, 600)?>)"></a>
                            </div>
                        <?php endif?>
                        <?php $i++; endforeach?>
                </div>


            </div>
        <?php elseif(count($feed['images']) == 4):?>
            <div class="four-images clearfix">
                <div class="col-sm-7 left">
                    <?php $i = 1; foreach($feed['images'] as $id => $image):?>
                        <?php if($i == 1):?>
                            <a data-image="<?php echo url_img($image, 920)?>" data-id="<?php echo $id?>" class="photo-viewer"  href="" style="background-image: url(<?php echo url_img($image, 600)?>)"></a>
                        <?php else: break;endif?>
                        <?php $i++; endforeach?>
                </div>
                <div class="col-sm-5 right">
                    <?php $i = 1; foreach($feed['images'] as $id => $image):?>
                        <?php if($i > 1):?>
                            <div>
                                <a data-image="<?php echo url_img($image, 920)?>" data-id="<?php echo $id?>" class="photo-viewer"  href="" style="background-image: url(<?php echo url_img($image, 600)?>)"></a>
                            </div>
                        <?php endif?>
                        <?php $i++; endforeach?>
                </div>


            </div>
        <?php else:?>
            <div class="five-images">
                <div class="top clearfix">
                    <div class="left">
                        <?php $i = 1; foreach($feed['images'] as $id => $image):?>
                            <?php if($i == 1):?>
                                <a data-image="<?php echo url_img($image, 920)?>" data-id="<?php echo $id?>" class="photo-viewer" href="" style="background-image: url(<?php echo url_img($image, 600)?>)"></a>
                            <?php else: break;endif?>
                            <?php $i++; endforeach?>
                    </div>
                    <div class="right">
                        <?php $i = 1; foreach($feed['images'] as $id => $image):?>
                            <?php if($i == 2):?>
                                <a data-image="<?php echo url_img($image, 920)?>" data-id="<?php echo $id?>" class="photo-viewer" href="" style="background-image: url(<?php echo url_img($image, 600)?>)"></a>
                            <?php endif?>
                            <?php $i++; endforeach?>
                    </div>
                </div>
                <div class="bottom clearfix">
                    <?php $i = 1; foreach($feed['images'] as $id => $image):?>
                        <?php if($i > 2 and $i <= 5):?>
                            <div>
                                <a data-image="<?php echo url_img($image, 920)?>" data-id="<?php echo $id?>" class="photo-viewer" href="" style="background-image: url(<?php echo url_img($image, 600)?>)">
                                    <?php if ($i == 5 and count($feed['images']) > 5):?>
                                        <div class="more-images">+<?php echo count($feed['images']) - 5?></div>
                                    <?php endif?>
                                </a>

                            </div>
                        <?php endif?>
                        <?php $i++; endforeach?>
                </div>


            </div>
        <?php endif?>
    </div>
<?php endif?>
<?php if(plugin_loaded('music') && $feed['music']): ?>
<?php load_functions('music::music') ?>
    <?php if(is_numeric($feed['music'])): ?>
        <?php $music = (isset($feed['musicDetails'])) ? $feed['musicDetails'] : get_music($feed['music']); ?>
        <?php //exit(var_dump($music)); ?>
        <?php if($music): ?>
            <div class="feed-music-player-container">
            <?php if($music['source'] == 'upload'): ?>
                <?php if($music['status'] == 0): ?>
                <div class="music-in-processing"><?php echo lang('music::music-in-processing') ?></div>
                <?php else: ?>
                <?php echo view('music::feed_music', array('music' => $music)) ?>
                <?php endif ?>
            <?php else: ?>
                <div class="external-music"><?php echo $music['code'] ?></div>
            <?php endif ?>
                <div class="music-title" style="min-height: 40px">
                    <a ajax="true" href="<?php echo get_music_url($music) ?>"><?php echo empty($music['artist']) ? $music['title'] : $music['artist'].' - '.$music['title'] ?></a>
                    <span class="plays"><i class="ion-play"></i> <?php echo $music['play_count'] ?> <?php echo $music['play_count'] > 1 ? lang('music::plays') : lang('music::play') ?></span>
                </div>
            </div>
        <?php endif ?>
    <?php else: ?>
    <iframe style="border: none; padding: 0px !important; margin:0px 10px; border-radius: 3px; overflow: hidden; width: 96%;" src="<?php echo $feed['music'] ?>"></iframe>
    <?php endif ?>
<?php endif ?>

<?php if($feed['video']):?>
    <?php if(is_numeric($feed['video'])):?>
            <?php $video = (isset($feed['videoDetails'])) ? $feed['videoDetails'] : null;?>

            <?php if($video):?>
                <div class="feed-video-player-container">
                    <?php if($video['source'] == 'upload'):?>
                        <?php if($video['status'] == 0):?>
                            <div class="video-in-processing">
                                <?php _lang('video::video-in-processing')?>
                            </div>
                        <?php else:?>
                            <iframe class="" allowfullscreen="true" webkitallowfullscreen="true" mozallowfullscreen="true" style="border: none;padding: 0 !important;border-radius: 3px;overflow: hidden;width: 100%;" src="<?php echo url_to_pager("play-video").'?link='.$video['file_path']?>&height=430" width="100%" height="450"></iframe>
                        <?php endif?>
                    <?php else:?>
                        <div class="external-video"><?php echo set_youtube_param($video['code'], array('rel' => 0)) ?></div>
                    <?php endif?>
                    <div class="video-title" style="min-height: 40px">
                        <a ajax="true" href="<?php echo get_video_url($video)?>"><?php echo $video['title']?></a>
                        <span class="views"> <i class="ion-ios-eye"></i> <?php echo $video['view_count']?>  <?php _lang('video::views')?></span>
                    </div>

                </div>
            <?php endif?>
        <?php else:?>
        <iframe allowfullscreen="true" webkitallowfullscreen="true" mozallowfullscreen="true" style="border: none;padding: 0 !important;margin:0 10px;border-radius: 3px;overflow: hidden;width: 96%" src="<?php echo url_to_pager("play-video").'?link='.$feed['video']?>" width="94%" height="330"></iframe>
        <?php endif?>

<?php endif?>


<?php if($feed['files']):?>
    <div class="feed-files">
        <?php foreach($feed['files'] as $id => $file):?>
            <?php if(isset($file['extension'])):?>
                <div class="media">
                    <div class="media-left">
                        <div><img src="<?php echo img('images/file-icons/'.$file['extension'].'.png')?>"/></div>
                    </div>
                    <div class="media-body">
                        <h5 class="media-heading"><?php echo $file['name']?></h5>
                        <?php if(config('allow-guest-download-file', true) or is_loggedIn()):?>
                            <a data-toggle="tooltip" title="<?php _lang('download-file')?>" href="<?php echo url_to_pager('feed-download')?>?file=<?php echo $file['path']?>&name=<?php echo $file['name']?>" class="btn btn-secondary-outline btn-sm"><i class="ion-android-download"></i></a>
                        <?php endif?>
                    </div>
                </div>
                <?php endif?>
        <?php endforeach?>
    </div>
<?php endif?>

<?php theme_extend("feed.content", null, array($feed))?>

<?php if($feed['location']):$location=$feed['location']?>
    <?php $key = trim(config('google-api-key', '') != '') ? '&key='.config('google-api-key', '') : '' ?>
    <img style="width: 100%;margin-top: 10px" class="post-location-image" src="https://maps.googleapis.com/maps/api/staticmap?center=<?php echo $location?>&zoom=15&size=700x200&maptype=roadmap&markers=color:red%7C<?php echo $location?>&sensor=false&scale=1&visual_refresh=true<?php echo $key ?>"/>
<?php endif?>

<?php if($feed['is_poll']):?>
    <div class="feed-poll" id="feed-poll-<?php echo $feed['feed_id']?>">
        <?php echo view("feed::poll-result", array('feed' => $feed));?>

    </div>
<?php endif?>

<?php if($feed['link_details']):?>
    <?php echo view('feed::link', array('details' => perfectUnserialize($feed['link_details'])))?>
<?php endif?>