<div class="lg-title" style="background: #CF000F;color: #ffffff"><?php _lang('404-not-found')?></div>
<div class="container">
    <div class="panel-container card">
        <div class="card-block" style="text-align: center">
            <i class="ion-alert-circled" style="margin: 20px;font-size: 80px"></i>
            <h4><?php _lang('page-not-available')?>
            </h4>
            <h6><?php _lang('page-not-available-note')?></h6>


        </div>
    </div>

</div>