<?php $videos = get_videos('browse', 'all', null,  null, $limit, 'featured');?>
<?php if($videos->total):?>
    <div class="box">
        <div class="title"><?php _lang('video::featured-videos')?></div>
        <div class="box-content" id="video-widget">
            <?php foreach($videos->results() as $video):?>
                <div class="media media-lg user">
                    <div class="media-left"><a ajax="true" href="<?php echo get_video_url($video)?>"><div class="media-object"style="background-image: url(<?php echo $video['photo_path'] ? url_img($video['photo_path'], 75) : img('video::images/preview.png', 75) ?>); background-position: center; background-size: cover;"></div></a></div>
                    <div class="media-body">
                        <a ajax="true" href="<?php echo get_video_url($video)?>"><h6 class="media-heading" style="font-weight: normal"><?php echo ($video['title']) ? $video['title'] : lang('video::untitled-video')?></h6></a>
                        <p class="help-block"><?php echo str_limit($video['description'], 100)?></p>
                    </div>
                </div>
            <?php endforeach?>
        </div>
    </div>
<?php endif?>