<div class="wrapper">
    <div class="wrapper-title">
        <p><?php echo lang('marketplace::delete-listing') ?></p>
        <span><?php echo lang('marketplace::delete-listing-desc') ?></span>
    </div>
    <div class="wrapper-content">
        <?php if($messages): ?>
            <div class="alert alert-danger"><?php echo $messages ?></div>
        <?php endif ?>
        <form action="" method="post" class="adm">
			<?php CSRFProtection::embed() ?>
            <div class="alert alert-warning"><?php echo lang('marketplace::delete-warning')?> <strong><?php echo $listing['title'] ?></strong>?</div>
            <div class="row">
                <div class="col-sm-5"></div>
                <div class="col-sm-7">
                    <input type="submit" value="<?php echo lang('marketplace::delete') ?>" class="btn btn-danger" />
                </div>
            </div>
            <input type="hidden" name="val[listing_id]" value="<?php echo $listing['id'] ?>" />
            <input type="hidden" name="val[type]" value="delete_listing" />
        </form>
    </div>
</div>