

<div class="box-content" style="padding: 10px">
    <div class="media media-lg">

        <div class="media-body">
            <div class="pull-left">
                <h3><?php echo $album['title']?></h3>
                <div class="help-block"><?php echo $album['description']?></div>

            </div>

            <?php if (can_manage_photo_album($album)):?>
                <span class="pull-right">
                                    <a ajax="true" href="<?php echo profile_url('photos/album/edit/'.$album['id'])?>" class="btn btn-info-outline btn-sm "><i class="ion-edit"></i> <?php _lang('photo::edit-album')?></a>
                                    <a onclick="return delete_photo_album('<?php echo _lang('photo::delete-album-message')?>', '<?php echo url_to_pager('photo-album-delete', array('id' => $album['id']))?>')" href="<?php echo url_to_pager('photo-album-delete', array('id' => $album['id']))?>" class="btn btn-danger-outline btn-sm"><i class="ion-android-delete"></i></a>
                                </span>
            <?php endif?>
        </div>
    </div>
</div>


<div id="photos-list" class="photos-list box-content clearfix" style="padding: 10px" data-type="album" data-id="<?php echo $album['id']?>" data-offset="0">
    <?php if(can_manage_photo_album($album)):?>

        <div class="photo upload-photo">
            <form data-error="Something went wrong. try again" action="" method="post" enctype="multipart/form-data">
				<?php CSRFProtection::embed() ?>
                <span class="file-input"><input  onchange="upload_album_photos('<?php echo $album['id']?>')" multiple type="file" id="album-photo-upload-input" name="photos[]"/> </span>
                <a onclick="return file_chooser('#album-photo-upload-input')" href="">
                    <i  class="ion-ios-cloud-upload-outline"></i>
                    <span><?php _lang('photo::add-photos')?></span>
                </a>
            </form>
            <div class="indicator">
                <img src="<?php echo img('images/loading.gif')?>"/>
                <?php _lang('photo::uploading')?><span>0%</span>
            </div>
        </div>
    <?php endif?>


    <?php foreach($photos as $photo):?>
        <?php echo view('photo::display-photo', array('id' => $photo['id'], 'image' => $photo['path']))?>
    <?php endforeach?>
</div>

<?php if($photos):?>
    <a id="photos-list-indicator" href="" onclick="return paginate_album_photos()" class="title" style="display: block;text-align: center">
        <?php _lang('view-more')?>
        <img src="<?php echo img('images/loading.gif')?>" style="width: 10px;display: none"/>
    </a>
<?php endif?>