<div class="box">
    <div class="title"><?php _lang('photo::edit-album')?></div>
    <div class="box-content" style="padding: 10px 10%">
        <?php if($message):?>
            <div class="alert alert-danger"><?php echo $message?></div>
        <?php endif?>
        <form action="" method="post">
			<?php CSRFProtection::embed() ?>
            <div class="form-group row">
                <label class="control-label col-sm-4"><?php _lang('photo::album-title')?></label>
                <div class="col-sm-8">
                    <input value="<?php echo $album['title']?>" type="text" name="val[name]" class="form-control"/>
                </div>
            </div>
            <div class="form-group row">
                <label class="control-label col-sm-4"><?php _lang('photo::album-description')?></label>
                <div class="col-sm-8">
                    <textarea name="val[description]" data-height="100px" style="height: 100px" class="form-control auto-grow-input"><?php echo $album['description']?></textarea>
                </div>
            </div>
            <div class="form-group row">
                <label class="control-label col-sm-4"><?php _lang('photo::album-privacy')?></label>
                <div class="col-sm-8">
                    <select name="val[privacy]" class="c-select">
                        <option <?php echo ($album['privacy'] == 1) ? 'selected' : null?> value="1"><?php _lang('public')?></option>
                        <option <?php echo ($album['privacy'] == 2) ? 'selected' : null?> value="2"><?php echo (config('relationship-method', 3) == 1) ? lang('feed::followers-only') : lang('feed::friends-only')?></option>
                        <option <?php echo ($album['privacy'] == 3) ? 'selected' : null?> value="3"><?php echo lang('feed::only-me')?></option>
                    </select>
                </div>
            </div>
            <button class="btn btn-primary"><?php _lang('photo::save-album')?></button>
        </form>
    </div>
</div>