<div class="box">
    <div class="title"><?php _lang('change-your-password')?></div>
    <div class="box-content" style="padding:30px 10%">
        <p class="help-block">
            <?php _lang('change-password-info')?>
        </p>
        <?php if($message):?>
            <div class="alert alert-danger"><?php echo $message?></div>
        <?php endif?>
        <?php if($success):?>
            <div class="alert alert-success"><?php echo $success?></div>
        <?php endif?>
        <form action="" method="post">
			<?php CSRFProtection::embed() ?>
            <div class="form-group">
                <label><?php _lang('current-password')?></label>
                <input class="form-control" type="password" name="val[current]" placeholder=""/>
            </div>

            <div class="dropdown-divider"></div>

            <div class="form-group row">
                <label class="col-md-4 form-control-label"><?php _lang('new-password')?></label>
                <div class="col-md-8">
                    <input class="form-control" type="password" name="val[new]" placeholder=""/>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-md-4 form-control-label"><?php _lang('confirm-new-password')?></label>
                <div class="col-md-8">
                    <input class="form-control" type="password" name="val[confirm]" placeholder=""/>
                </div>
            </div>

            <div class="divider"></div>
            <button class="btn btn-info"><?php _lang('change')?></button>
        </form>
    </div>
</div>