<div class="wrapper">
    <div class="wrapper-title">
        <?php _lang('manage-members')?>
        <span><?php _lang('manage-members-desc')?></span>
    </div>
    <div class="wrapper-content">
        <form method="post" action="" class="wrapper-form">
			<?php CSRFProtection::embed() ?>
            <div class="form-group row">
                <label class="col-sm-3 form-control-label"><?php _lang('first_name')?></label>
                <div class="col-sm-9">
                    <input type="text" class="form-control" name="val[first_name]" value="<?php echo $user['first_name']?>"/>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-sm-3 form-control-label"><?php _lang('last_name')?></label>
                <div class="col-sm-9">
                    <input type="text" class="form-control" name="val[last_name]" value="<?php echo $user['last_name']?>"/>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-sm-3 form-control-label"><?php _lang('username')?></label>
                <div class="col-sm-9">
                    <input type="text" class="form-control" name="val[username]" value="<?php echo $user['username']?>"/>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-sm-3 form-control-label"><?php _lang('email-address')?></label>
                <div class="col-sm-9">
                    <input type="text" class="form-control" name="val[email_address]" value="<?php echo $user['email_address']?>"/>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-sm-3 form-control-label"><?php _lang('password')?></label>
                <div class="col-sm-9">
                    <input type="password" class="form-control" name="val[password]" value=""/>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-sm-3 form-control-label"><?php _lang('verified')?></label>
                <div class="col-sm-9">
                    <select name="val[verified]">
                        <option <?php echo ($user['verified'] == 0) ? 'selected' : null?> value="0"><?php _lang('no')?></option>
                        <option  <?php echo ($user['verified'] == 1) ? 'selected' : null?> value="1"><?php _lang('yes')?></option>
                    </select>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-sm-3 form-control-label"><?php _lang('activated')?></label>
                <div class="col-sm-9">
                    <select name="val[activated]">
                        <option <?php echo ($user['activated'] == 0) ? 'selected' : null?> value="0"><?php _lang('no')?></option>
                        <option  <?php echo ($user['activated'] == 1) ? 'selected' : null?> value="1"><?php _lang('yes')?></option>
                    </select>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-sm-3 form-control-label"><?php _lang('banned')?></label>
                <div class="col-sm-9">
                    <select name="val[bannned]">
                        <option <?php echo ($user['bannned'] == 0) ? 'selected' : null?> value="0"><?php _lang('no')?></option>
                        <option  <?php echo ($user['bannned'] == 1) ? 'selected' : null?> value="1"><?php _lang('yes')?></option>
                    </select>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-sm-3 form-control-label"><?php _lang('featured')?></label>
                <div class="col-sm-9">
                    <select name="val[featured]">
                        <option <?php echo ($user['featured'] == 0) ? 'selected' : null?> value="0"><?php _lang('no')?></option>
                        <option  <?php echo ($user['featured'] == 1) ? 'selected' : null?> value="1"><?php _lang('yes')?></option>
                    </select>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-sm-3 form-control-label"><?php _lang('role')?></label>
                <div class="col-sm-9">
                    <select name="val[role]">
                        <?php $userRole = ($user['role']) ? $user['role'] : 2;?>
                       <?php foreach(list_user_roles() as $role):?>
                            <option <?php echo ($role['role_id'] == $userRole) ? 'selected' : null?> value="<?php echo $role['role_id']?>"><?php echo $role['role_title']?></option>
                        <?php endforeach?>
                    </select>
                </div>
            </div>


            <button class="btn btn-info"><?php _lang('save')?></button>
        </form>
    </div>
</div>