<div class="wrapper">
    <div class="wrapper-title">
        <?php echo lang('music::music-categories') ?>
        <a class="btn btn-sm btn-danger" href="<?php echo url_to_pager('admin-music-add-category-pager') ?>"><?php echo lang('music::add-category') ?></a>
    </div>
    <div class="wrapper-content">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th style="width: 5%">ID</th>
                    <th style="width: 55%"><?php echo lang('title') ?></th>
                    <th style="width: 40%"><?php echo lang('actions') ?></th>
                </tr>
            </thead>
            <tbody data-url="<?php echo url_to_pager('admin-music-manage-category').'?action=order&id='.input('id') ?>" class="admincp-sortable">
                <?php foreach($categories as $category): ?>
                    <tr class="item" id="<?php echo $category['id'] ?>">
                        <td><?php echo $category['id'] ?></td>
                        <td>

                            <?php if(!input('id')): ?>
                                <a href="<?php echo url_to_pager('admin-music-categories-pager').'?id='.$category['id'] ?>"><?php echo lang($category['title']) ?></a>
                            <?php else: ?>
                                <?php echo lang($category['title']) ?>
                            <?php endif ?>
                        </td>
                        <td>
                            <?php if(!input('id')): ?>
                                <a href="<?php echo url_to_pager('admin-music-categories-pager').'?id='.$category['id'] ?>" class="btn btn-sm btn-secondary"><?php echo lang('music::manage-categories') ?></a>
                            <?php endif ?>
                            <a href="<?php echo url_to_pager('admin-music-manage-category').'?action=edit&id='.$category['id'] ?>" class="btn btn-info btn-sm"><?php echo lang('edit') ?></a>
                            <a href="<?php echo url_to_pager('admin-music-manage-category').'?action=delete &id='.$category['id'] ?>" class="btn btn-danger btn-sm"><?php echo lang('delete') ?></a>
                        </td>
                    </tr>
                <?php endforeach ?>
            </tbody>
        </table>
    </div>
</div>