        </div>
        <div class="modal fade" id="loginModal">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header"><h4 class="modal-title"><?php echo lang('login') ?></h4><button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>
                    <div class="modal-body">
                        <form action="<?php echo url_to_pager('login') ?>" method="post">
                            <?php CSRFProtection::embed() ?>
                            <fieldset class="form-group"><input type="text" class="form-control form-control-lg" name="val[username]"  placeholder="<?php echo lang('username-email-address') ?>"></fieldset>
                            <fieldset class="form-group"><input type="password" class="form-control form-control-lg" name="val[password]" placeholder="<?php echo lang('your-password') ?>"></fieldset>
                            <div class="clearfix">
                                <div class="checkbox pull-left"><label class="c-input c-checkbox"><input name="val[remember]" checked type="checkbox"><span class="c-indicator"></span><?php echo lang('remember-me') ?></label></div>
                                <a ajax="true" href="<?php echo url_to_pager('forgot-password') ?>" class="pull-right"><?php echo lang('forgot-password') ?></a>
                            </div>
                            <button class="btn btn-secondary btn-block btn-upper"><?php echo lang('sign-in') ?></button>
                        </form>
                        <?php if(config('enable-facebook', false) || config('enable-twitter', false) || config('enable-googleplus', false) || config('enable-vk', false)): ?>
                            <div id="social-links-container">
                                <div class="sign-with-container">
                                    <div class="text"><?php _lang('login-with')?></div>
                                    <div class="line"></div>
                                </div>
                                <div class="content">
                                    <ul id="home-social-links">
                                        <?php if(config('enable-facebook', false)):?>
                                            <li><a class="facebook" href="<?php echo url_to_pager('facebook-auth')?>"><i class="icon ion-social-facebook"></i> </a></li>
                                        <?php endif?>
                                        <?php if(config('enable-twitter', false)):?>
                                            <li><a class="twitter" href="<?php echo url_to_pager('twitter-auth')?>"><i class="icon ion-social-twitter"></i> </a> </li>
                                        <?php endif?>
                                        <?php if(config('enable-googleplus', false)):?>
                                            <li><a class="googleplus" href="<?php echo url_to_pager('googleplus-auth')?>"><i class="ion-social-googleplus-outline"></i> </a> </li>
                                        <?php endif?>
                                        <?php if(config('enable-vk', false)):?>
                                            <li><a class="vk" href="<?php echo url_to_pager('vk-auth')?>"><i class="ion-android-arrow-forward"></i> </a> </li>
                                        <?php endif?>
                                    </ul>
                                </div>
                            </div>
                        <?php endif ?>
                    </div>
                </div>
            </div>
        </div>
        <div id="footer">
            <div class="container">
                <?php echo view('layouts/column/load', array('position' => 'bottom', 'page' => 'footer', 'content' => '')) ?>
            </div>
            <div class="container footer-content <?php echo $app->hideFooterContent ? 'hide-footer' : null ?>">
                <?php $footer_menus = get_menus("footer-menu") ?>
                <?php if(!empty($footer_menus)): ?>
                <div><ul id="footer-links"><?php foreach( $footer_menus as $menu): ?><li><a href="<?php echo $menu->link ?>"><?php echo ucfirst(lang($menu->title)) ?></a></li><?php endforeach ?></ul></div>
                <?php endif ?>
                <div id="footer-copyright"><?php echo lang('copyright') ?> © <?php echo date('Y') ?> <?php echo config('site_title') ?>. <?php echo lang('all-right-reserved') ?> <?php echo lang('powered-by') ?> <?php echo config('site_title') ?>.</div>
                <div><ul><?php $started = false; foreach(get_all_languages() as $lang): ?><li><a style="<?php echo ($lang['language_id'] == $app->lang) ? 'font-weight:bold' : null ?>" href="<?php echo url_to_pager("change-language", array('lang' => $lang['language_id'])) ?>"><?php echo $lang['language_title'] ?></a>  </li><?php endforeach ?></ul></div>
            </div>
        </div>
        <div id="confirmModal" class="modal fade " tabindex="-1" role="dialog" aria-labelledby="confirmModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-sm">
                <div class="modal-content">
                    <div class="modal-body" data-message="<?php echo lang('are-you-sure') ?>"><?php echo lang('are-you-sure') ?></div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal"><?php echo lang('no') ?></button>
                        <button type="button" id="confirm-button" class="btn btn-secondary"><?php echo lang('yes') ?></button>
                    </div>
                </div>
            </div>
        </div>
        <div id="alertModal" class="modal fade " tabindex="-1" role="dialog" aria-labelledby="confirmModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-sm">
                <div class="modal-content">
                    <div class="modal-body">
                    </div>
                    <div class="modal-footer"><button type="button"  data-dismiss="modal" aria-label="Close" class="btn btn-primary btn-sm"><?php echo lang('ok') ?></button></div>
                </div>
            </div>
        </div>
        <?php echo theme_extend("footer") ?>
        <?php echo render_assets('js') ?>
        <script src="<?php echo asset_link("js/tinymce/tinymce.min.js") ?>"></script>
        <script src="<?php echo asset_link("js/tinymce/jquery.tinymce.min.js") ?>"></script>
        <?php $key = trim(config('google-api-key', '') != '') ? '&key='.config('google-api-key', '') : '' ?>
        <script src="https://maps.googleapis.com/maps/api/js?libraries=places<?php echo $key ?>"></script>
        <audio id="update-sound" preload="auto">
            <source src="<?php echo asset_link('sounds/notification.ogg') ?>" type="audio/ogg">
            <source src="<?php echo asset_link('sounds/notification.mp3') ?>" type="audio/mpeg">
            <source src="<?php echo asset_link('sounds/notification.wav') ?>" type="audio/wav">
        </audio>
    </body>
</html>