<div class="wrapper">
    <div class="wrapper-title">
        <?php _lang("announcement::add-new")?>

    </div>

    <div class="wrapper-content">
        <form method="post" action="" class="wrapper-form">
            <?php CSRFProtection::embed() ?>
            <div class="form-group row">
                <label class="col-sm-3 form-control-label"><?php _lang('announcement::type')?></label>
                <div class="col-sm-9">
                    <select class="c-select" name="val[type]">
                        <option <?php echo ($announcement['type'] == 'success') ? 'selected' : null?> value="success"><?php _lang('announcement::success')?></option>
                        <option <?php echo ($announcement['type'] == 'warning') ? 'selected' : null?> value="warning"><?php _lang('announcement::warning')?></option>
                        <option <?php echo ($announcement['type'] == 'danger') ? 'selected' : null?> value="danger"><?php _lang('announcement::danger')?></option>
                        <option <?php echo ($announcement['type'] == 'info') ? 'selected' : null?> value="info"><?php _lang('announcement::info')?></option>
                    </select>
                </div>
            </div>



            <div class="form-group row">
                <label class="col-sm-3 form-control-label"><?php _lang('announcement::content')?></label>
                <div class="col-sm-9">

                    <?php foreach(get_all_languages() as $language):?>
                        <textarea name="val[content][<?php echo $language['language_id']?>]" class="form-control" placeholder="<?php _lang('announcement::content')?>"><?php echo get_phrase($language['language_id'], $announcement['content'])?></textarea>
                        <p class="help-block"><strong><?php echo  $language['language_title']?></strong></p>
                    <?php endforeach?>
                </div>
            </div>

            <h5><?php _lang('announcement::display-options')?></h5>
            <hr/>

            <div class="form-group row">
                <label class="col-sm-3 form-control-label"><?php _lang('active')?></label>
                <div class="col-sm-9">

                    <div class="c-inputs-stacked">
                        <label class="c-input c-radio">
                            <input <?php echo ($announcement['active'] == '1') ? 'checked' : null?> id="radioStacked1" value="1" name="val[active]" type="radio">
                            <span class="c-indicator"></span>
                            <?php _lang('yes')?>
                        </label>
                        <label class="c-input c-radio">
                            <input <?php echo ($announcement['active'] == '0') ? 'checked' : null?> id="radioStacked2" name="val[active]" value="0" type="radio">
                            <span class="c-indicator"></span>
                            <?php _lang('no')?>
                        </label>
                    </div>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-sm-3 form-control-label"><?php _lang('announcement::can-be-close')?></label>
                <div class="col-sm-9">

                    <div class="c-inputs-stacked">
                        <label class="c-input c-radio">
                            <input <?php echo ($announcement['can_close'] == '1') ? 'checked' : null?> id="radioStacked1" value="1" name="val[closed]" type="radio">
                            <span class="c-indicator"></span>
                            <?php _lang('yes')?>
                        </label>
                        <label class="c-input c-radio">
                            <input <?php echo ($announcement['can_close'] == '0') ? 'checked' : null?>  id="radioStacked2" name="val[closed]" value="0" type="radio">
                            <span class="c-indicator"></span>
                            <?php _lang('no')?>
                        </label>
                    </div>
                </div>
            </div>



            <h5><?php _lang('announcement::target-viewers')?></h5>
            <hr/>
            <div class="form-group row">
                <label class="col-sm-3 form-control-label"><?php _lang('announcement::user-group')?></label>
                <div class="col-sm-9">

                    <select name="val[role]" class="c-select">
                        <option <?php echo ($announcement['user_group'] == '0') ? 'selected' : null?> class="all" value="0"><?php _lang('announcement::any')?></option>
                        <?php foreach(list_user_roles() as $role):?>
                        <option <?php echo ($announcement['user_group'] == $role['role_id']) ? 'selected' : null?>   value="<?php echo $role['role_id']?>"><?php echo $role['role_title']?></option>
                        <?php endforeach?>
                        <option <?php echo ($announcement['user_group'] == '100') ? 'selected' : null?>  value="100"><?php _lang('announcement::guests')?></option>
                    </select>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-sm-3 form-control-label"><?php _lang('announcement::location')?></label>
                <div class="col-sm-9">

                    <select name="val[location]" class="c-select">

                        <option class="all" value="any"><?php _lang('announcement::any')?></option>
                        <?php load_functions('country'); foreach(get_countries() as $country => $name):?>
                            <option <?php echo ($announcement['location'] == $name) ? "selected" : null?> value="<?php echo $name?>"><?php echo ucwords($name)?></option>
                        <?php endforeach?>
                    </select>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-sm-3 form-control-label"><?php _lang('gender')?></label>
                <div class="col-sm-9">

                    <select name="val[gender]" class="c-select">

                        <option <?php echo ($announcement['gender'] == 'any') ? "selected" : null?> class="all"><?php _lang('announcement::any')?></option>
                        <option <?php echo ($announcement['gender'] == 'male') ? "selected" : null?>  value="male"><?php _lang('male')?></option>
                        <option <?php echo ($announcement['gender'] == 'female') ? "selected" : null?>  value="female"><?php _lang('female')?></option>
                    </select>
                </div>
            </div>
            <button class="btn btn-info"><?php _lang('save')?></button>
        </form>
    </div>
</div>