<div class="container">
    <div class="box photo-viewer-container">
        <div class="navigate nav-left">
            <?php if($photo['imageBefore']):?>
                <a ajax="true"  class="" href="<?php echo url_to_pager('photo-view-pager', array('id' => $photo['imageBefore']['id']))?>"><i class="ion-ios-arrow-back"></i></a>
            <?php endif?>

        </div>
        <img src="<?php echo url_img($photo['path'], 920)?>"/>

        <div class="navigate nav-right">
            <?php if($photo['imageAfter']):?>
                <a  ajax="true" class="" href="<?php echo url_to_pager('photo-view-pager', array('id' => $photo['imageAfter']['id']))?>"><i class="ion-ios-arrow-forward"></i></a>
            <?php endif?>
        </div>
    </div>

    <div class="box">
        <div class="box-content">
            <?php echo view('photo::viewer/right', array('photo' => $photo))?>
        </div>
    </div>
</div>