<div class="box">
    <div class="box-content" style="padding: 20px 10%">
        <?php if($message):?>
            <div class="alert alert-danger"><?php echo $message?></div>
        <?php endif?>
        <?php
            $current = (config('video-upload', false) and config('video-encoder', 'none') != 'none') ? 'upload' : 'external';
        ?>
        <form action="" method="post" enctype="multipart/form-data">
            <?php CSRFProtection::embed() ?>
            <input type="hidden" name="val[entity_type]" value="<?php echo input('type', 'user')?>"/>
            <input type="hidden" name="val[entity_id]" value="<?php echo input('id', get_userid())?>"/>
            <div class="form-group row">
                <label class="control-label col-sm-4"><?php _lang('video::source')?></label>
                <div class="col-sm-8">
                    <select onchange="return change_video_source(this)" name="val[source]" class="c-select">
                        <?php if(config('video-upload', false)):?>
                            <option <?php echo ($current == 'upload') ? 'selected' : null?> value="upload"><?php _lang('video::upload-from-computer')?></option>
                        <?php endif?>
                        <option <?php echo ($current == 'external') ? 'selected' : null?> value="external"><?php _lang('video::external-link')?></option>
                    </select>

                    <div class="video-source-selector" style="margin-top: 20px">
                        <?php if(config('video-upload', false)):?>
                            <div class=" source upload <?php echo ($current == 'external') ? 'video-hide-field' : null?>" >
                                <input type="file" id="file" name="video_file">
                            </div>
                        <?php endif?>
                        <div class="source external <?php echo ($current == 'upload') ? 'video-hide-field' : null?>">
                            <div class="form-group ">
                                <input value="<?php echo input('val.link')?>" name="val[link]" type="text" class="form-control">
                                <span class="help-block"><?php _lang('video::external-url-info')?></span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="form-group row">
                <label class="control-label col-sm-4"><?php _lang('category')?></label>
                <div class="col-sm-8">
                    <select name="val[category_id]" class=" c-select" >
                        <?php foreach(get_video_categories() as $category):?>
                            <?php $subCategories = get_video_parent_categories($category['id'])?>
                            <?php if($subCategories):?>
                                <optgroup label="<?php _lang($category['title'])?>">

                                    <?php foreach($subCategories as $cat):?>
                                        <option value="<?php echo $cat['id']?>"><?php _lang($cat['title'])?></option>
                                    <?php endforeach?>
                                </optgroup>
                            <?php else:?>
                                <option value="<?php echo $category['id']?>"><?php _lang($category['title'])?></option>
                            <?php endif?>
                        <?php endforeach?>
                    </select>
                </div>
            </div>

            <div class="video-details-container <?php echo ($current == 'external') ? "video-hide-field" : null?>" >
                <div class="form-group row">
                    <label class="control-label col-sm-4"><?php _lang('video::title')?></label>
                    <div class="col-sm-8">
                        <input value="<?php echo input('val.title')?>" type="text" name="val[title]" class="form-control"/>
                    </div>
                </div>



                <div class="form-group row">
                    <label class="control-label col-sm-4"><?php _lang('video::description')?></label>
                    <div class="col-sm-8">
                        <textarea name="val[description]" class="form-control auto-grow-input"><?php echo input('val.description')?></textarea>
                    </div>
                </div>
            </div>


            <div class="form-group row">
                <label class="control-label col-sm-4"><?php _lang('privacy')?></label>
                <div class="col-sm-8">
                    <?php $default = config('default-video-privacy', 1);?>
                    <select class="c-select" name="val[privacy]">
                        <option <?php echo ($default == 1) ? 'selected' : null?> value="1" ><?php _lang('everyone')?></option>
                        <option <?php echo ($default == 2) ? 'selected' : null?> value="2"><?php echo (config('relationship-method', 2) == 2 or config('relationship-method', 2) == 3) ? lang('friends-only') : lang('followers-only')?></option>
                        <option <?php echo ($default == 3) ? 'selected' : null?> value="3"><?php _lang('only-me')?></option>
                    </select>
                </div>
            </div>


            <button class="btn btn-info"><?php _lang('video::add-video')?></button>
        </form>
    </div>
</div>