<div class="box">
    <div class="title">
        <?php echo $video['title']?>
        <a href="<?php echo url('video/delete?id='.$video['id'])?>" class="btn btn-danger action btn-sm confirm"><?php _lang('video::delete-video')?></a>
    </div>
    <div class="box-content" style="padding: 20px 10%">
        <?php if($message):?>
            <div class="alert alert-danger"><?php echo $message?></div>
        <?php endif?>
        <?php
        $current = (config('video-upload')) ? 'upload' : 'external';
        ?>
        <form action="" method="post" enctype="multipart/form-data">
			<?php CSRFProtection::embed() ?>
            <div class="form-group row">
                <label class="control-label col-sm-4"><?php _lang('category')?></label>
                <div class="col-sm-8">
                    <select name="val[category_id]" class=" c-select" >
                        <?php foreach(get_video_categories() as $category):?>
                            <?php $subCategories = get_video_parent_categories($category['id'])?>
                            <?php if($subCategories):?>
                                <optgroup label="<?php _lang($category['title'])?>">
                                    <?php foreach($subCategories as $cat):?>
                                        <option value="<?php echo $cat['id']?>"><?php _lang($cat['title'])?></option>
                                    <?php endforeach?>
                                </optgroup>
                            <?php else:?>
                                <option value="<?php echo $category['id']?>"><?php _lang($category['title'])?></option>
                            <?php endif?>
                        <?php endforeach?>
                    </select>
                </div>
            </div>

            <div class="form-group row">
                <label class="control-label col-sm-4"><?php _lang('video::title')?></label>
                <div class="col-sm-8">
                    <input value="<?php echo $video['title']?>" type="text" name="val[title]" class="form-control"/>
                </div>
            </div>



            <div class="form-group row">
                <label class="control-label col-sm-4"><?php _lang('video::description')?></label>
                <div class="col-sm-8">
                    <textarea name="val[description]" class="form-control auto-grow-input"><?php echo $video['description']?></textarea>
                </div>
            </div>


            <div class="form-group row">
                <label class="control-label col-sm-4"><?php _lang('privacy')?></label>
                <div class="col-sm-8">
                    <?php $default = $video['privacy'];?>
                    <select class="c-select" name="val[privacy]">
                        <option <?php echo ($default == 1) ? 'selected' : null?> value="1" ><?php _lang('everyone')?></option>
                        <option <?php echo ($default == 2) ? 'selected' : null?> value="2"><?php echo (config('relationship-method', 2) == 2 or config('relationship-method', 2) == 3) ? lang('friends-only') : lang('followers-only')?></option>
                        <option <?php echo ($default == 3) ? 'selected' : null?> value="3"><?php _lang('only-me')?></option>
                    </select>
                </div>
            </div>


            <button class="btn btn-info"><?php _lang('video::save-video')?></button>
        </form>
    </div>
</div>