<?php
    $location = (isset($location)) ? $location : 'main-menu';
?>
<div class="row">
    <div class="col-sm-4">
        <div class="box">
            <div class="title"><?php _lang('available-menus')?></div>
            <div class="box-content" id="available-menus">
                <?php foreach(get_available_menus($location) as $menu):?>
                    <div data-title="<?php echo $menu['title']?>"
                         data-link="<?php echo $menu['link']?>"
                         data-icon="<?php echo $menu['icon']?>"
                         class="menu-item">
                        <?php echo _lang($menu['title'])?>
                    </div>
                <?php endforeach?>
            </div>
        </div>

        <div class="box">
            <div class="title"><?php _lang('add-link')?></div>
            <div class="box-content">
                <form action="" method="post" onsubmit="return siteEditor.submitLinkMenu(this)">
					<?php CSRFProtection::embed() ?>
                    <input type="hidden" name="val[location]" value="<?php echo $location?>"/>
                    <label><?php _lang('menu-title')?></label>
                    <input type="text" name="val[title][english]" class="form-control" value=""/>
                    <a href="" class="other-languages-link" onclick="return show_other_languages('#add-menu-other-languages')"><?php _lang('edit-other-languages')?></a>
                    <div class="other-languages" id="add-menu-other-languages">
                        <?php foreach(get_all_languages() as $language):?>
                            <?php if($language['language_id'] != 'english'):?>
                                <input class="form-control"  type="text" name="val[title][<?php echo $language['language_id']?>]" placeholder="<?php _lang('menu-title')?>"/><br>
                                <p class="help-block"><?php echo $language['language_title']?></p>
                            <?php endif?>
                        <?php endforeach?>
                    </div>
                    <label><?php _lang('link')?></label>
                    <input type="text" name="val[link]" class="form-control"/>

                    <label><?php _lang('icon')?></label>
                    <input type="text" name="val[icon]" class="form-control"/>
                    <p class="help-block">Ionic icons only , see here http://ionicons.com/cheatsheet.html</p>

                    <label class="c-input c-checkbox">
                        <input name="val[newtab]" value="1" type="checkbox">
                        <span class="c-indicator"></span>
                        <?php _lang('open-new-window')?>
                    </label>

                    <label class="c-input c-checkbox">
                        <input name="val[ajaxify]" value="1" type="checkbox">
                        <span class="c-indicator"></span>
                        <?php _lang('ajaxify')?>
                    </label>

                    <div class="clearfix" style="margin-top: 10px">

                        <button class="btn btn-info pull-right no-radius"><?php _lang('add-menu-item')?></button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="col-sm-8">
        <div class="box">
            <div class="box-content">
                <div class="row">
                    <div class="col-sm-4">
                        <label><?php _lang('menu-location')?></label>
                    </div>
                    <div class="col-sm-8">
                        <select onchange="return siteEditor.changeMenu(this)" id="menu-locations" class="c-select">
                            <?php foreach(get_menu_locations() as $id => $title):?>
                                <option <?php echo ($id == $location) ? 'selected' : null?> value="<?php echo $id?>"><?php _lang($title)?></option>
                            <?php endforeach?>
                        </select>
                    </div>
                </div>
            </div>
            <div class="title"><?php _lang('menu-structure')?></div>
            <div class="box-content">
                <div class="alert alert-warning"><strong><?php _lang('instructions')?>:</strong> <?php _lang('menu-drag-instruction')?></div>
                <div class="" id="menu-location-items">
                    <?php foreach(Menu::getSaveMenus($location) as $menu):?>
                        <div class="menu-item" id="<?php echo $menu['id']?>-menu">
                            <span class="menu-title"><?php _lang($menu['title'])?></span>
                            <a onclick="return siteEditor.editMenu('<?php echo $menu['id']?>')" href='' style='color:#009CEB'>Edit</a>
                            <a onclick="return siteEditor.deleteMenu('<?php echo $menu['id']?>')" href="" class="close" style="font-size: 15px"><i class="ion-close"></i></a> </div>
                    <?php endforeach?>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="edit-menu-modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form action="" method="post" onsubmit="return siteEditor.saveMenu(this)">
				<?php CSRFProtection::embed() ?>
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title"><?php _lang('edit-menu')?></h4>
                </div>
                <div class="modal-body">
                    <img style="width: 25px;margin: 20px 45%" src="<?php echo img('images/loader01.gif')?>" id="menu-loader"/>
                    <div class="edit-menu-content">

                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button  class="btn btn-primary"><?php _lang('save')?></button>
                </div>
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->