<div class="wrapper">
    <div class="wrapper-title">
        Manage Blogs
    </div>
    <div class="wrapper-content">
        <form action="" method="get" style="margin: 20px 0">
            <?php CSRFProtection::embed() ?>
            <input type="text" class="form-control" name="term" placeholder="<?php _lang('search')?>"/>

            <button class="btn btn-sm btn-secondary" style="margin-top: 10px"><?php echo _lang('search')?></button>
        </form>

        <table class="table table-bordered">
            <thead>
            <tr>
                <th>ID</th>
                <th><?php _lang('title')?></th>
                <th><?php _lang('blog::written-by')?></th>
                <th><?php _lang('blog::views')?></th>
                <th><?php _lang('status')?></th>
                <th><?php _lang('featured')?></th>
                <th><?php _lang('blog::last-update')?></th>
                <th><?php _lang('actions')?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach($blogs->results() as $blog):?>
                <tr class="item" id="<?php echo $blog['id']?>">
                    <td><?php echo $blog['id']?></td>
                    <td><a href="<?php echo url('blog/'.$blog['slug'])?>"><?php echo lang($blog['title'])?></a> </td>
                    <td>
                        <?php $user = find_user($blog['user_id'])?>
                        <a href="<?php echo profile_url(null, $user)?>"><?php echo get_user_name($user)?></a>
                    </td>
                    <td>
                        <?php echo $blog['views']?>
                    </td>
                    <td>
                        <?php echo ($blog['status']) ? 'Published' : 'Draft'?>
                    </td>
                    <td>
                        <?php echo ($blog['featured']) ? 'Yes' : 'No'?>
                    </td>
                    <td>
                        <?php echo date('d F Y  g:ia', $blog['update_time'])?>
                    </td>
                    <td>
                        <a href="<?php echo url_to_pager('admincp-blog-manage').'?action=edit&id='.$blog['id']?>"><?php _lang('edit')?></a>
                        <a href="<?php echo url_to_pager('admincp-blog-manage').'?action=delete&id='.$blog['id']?>"><?php _lang('delete')?></a>
                    </td>
                </tr>
            <?php endforeach?>
            </tbody>
        </table>

        <?php echo $blogs->links()?>
    </div>
</div>