<?php
$categories = forum_get_categories();
$category_id = input('c') ? input('c') : null;
$url = http_build_query($_GET) == '' ? url_to_pager("forum-slug", array('appends' => '')) : url_to_pager("forum-slug", array('appends' => '')).'?'.http_build_query($_GET);
?>
<div class="forum forum-categories box">
    <ul class="menu">
        <li class="<?php if(!$category_id): ?> active<?php endif ?>"><a href="<?php echo forum_get_forum_slug_link(forum_remove_get_var(forum_remove_get_var($url, 's'), 'c')) ?>" ajax="true"><?php echo lang('forum::all-categories') ?></a></li>
        <?php foreach($categories as $category): ?>
        <li class="<?php if($category_id == $category['id']): ?> active<?php endif ?>"><a href="<?php echo forum_get_forum_slug_link(forum_assign_get_var(forum_remove_get_var($url, 's'), 'c', $category['id'])) ?>" ajax="true"><?php echo lang($category['title']) ?></a></li>
        <?php endforeach ?>
    </ul>
</div>