<?php if(isset(app()->music)): ?>
    <?php $music = app()->music; $musics = get_related_musics($music, $limit); ?>
    <?php if($musics->total): ?>
        <div class="box">
            <div class="title"><?php echo lang('music::related-musics') ?></div>
            <div class="box-content" id="music-widget">
            <?php foreach($musics->results() as $music): ?>
                <div class="media media-lg user">
                    <div class="media-left"><a ajax="true" href="<?php echo get_music_url($music) ?>"><div class="media-object" style="background-image: url(<?php echo $music['cover_art'] ? url_img($music['cover_art'], 75) : img('music::images/preview.png', 75) ?>); background-position: center; background-size: cover;"></div></a></div>
                    <div class="media-body">
                        <a ajax="true" href="<?php echo get_music_url($music) ?>"><h6 class="media-heading" style="font-weight: normal"><?php echo ($music['title']) ? $music['title'] : lang('music::untitled-music') ?></h6></a>
                        <p class="help-block"><?php echo str_limit($music['artist'].' - '.$music['title'], 50) ?><br /><?php echo str_limit($music['album'], 50) ?></p>
                    </div>
                </div>
            <?php endforeach ?>
            </div>
        </div>
    <?php endif ?>
<?php endif ?>