<?php
$avatar = $feed['editor']['avatar'];
$entityId = $feed['editor']['id'];
$entityType = $feed['editor']['type'];
?>
<div data-error="<?php _lang('something-went-wrong-error') ?>" class="feed-hide-container"
     id="feed-hide-container-<?php echo $feed['feed_id'] ?>">
    <div class="col-sm-2 no-padding"></div>
    <div class="col-sm-10" style="padding: 0">
        <div class="box">
            <div class="box-content">
                <?php _lang('feed::feed-no-longer-show') ?> <a href=""
                                                               onclick="return unhide_feed('<?php echo $feed['feed_id'] ?>')"><?php _lang('undo') ?></a>
            </div>
        </div>
    </div>
</div>

<div id="feed-boost-wrapper-<?php echo $feed['feed_id'] ?>" class="feed-wrapper clearfix">
<input type="hidden" value="<?php echo $feed['feed_id']; ?>" id="add-id-of-this-feed" />
<script>
    var el = document.getElementById('feed-wrapper-'+<?php echo $feed['feed_id']; ?>);
    if(el != null){
        el.style.display = "none";
    }
</script>
<div class="col-sm-2  left no-padding">
    <a ajax="true" href="<?php echo $feed['publisher']['url'] ?>" class="avatar"><img
            src="<?php echo $feed['publisher']['avatar'] ?>"/> </a>

    <?php if (isset($feed['targetUser'])): ?>

        <a href="<?php echo profile_url(null, $feed['targetUser']) ?>" ajax="true" class="avatar"><img
                src="<?php echo get_avatar(75, $feed['targetUser']) ?>"/> </a>
    <?php endif ?>

    <?php if (isset($feed['tags-users']) and !isset($feed['targetUser'])): ?>

        <a ajax="true" class="avatar" href="<?php echo profile_url(null, $feed['tags-users'][0]) ?>"><img
                src="<?php echo get_avatar(75, $feed['tags-users'][0]) ?>" </a>
        <?php if ($feed['tagsCount'] > 1): ?>
            <div class="more-count">+<?php echo $feed['tagsCount'] - 1 ?></div>
        <?php endif ?>
    <?php endif ?>
</div>

<div class="col-sm-10  right no-padding">
<div class="box">

<div class="feed-header clearfix">
<div class="left">
    <a ajax="true" href="<?php echo $feed['publisher']['url'] ?>" class="avatar"><img
            src="<?php echo $feed['publisher']['avatar'] ?>"/> </a>
</div>
<div class="right">
    <div class="feed-title">
                   <span class=" preview-card" data-type="<?php echo $feed['entity_type'] ?>"
                         data-id="<?php echo $feed['entity_id'] ?>">
                       <a ajax="true" href="<?php echo $feed['publisher']['url'] ?>" class="">
                           <?php echo $feed['publisher']['name'] ?>
                           <?php echo verify_badge($feed['publisher']) ?>
                       </a>

                   </span>
        <?php if (isset($feed['targetUser'])): ?>
            <i class="ion-ios-arrow-thin-right"></i>
            <span class=" preview-card" data-type="user" data-id="<?php echo $feed['targetUser']['id'] ?>">
                            <a href="<?php echo profile_url(null, $feed['targetUser']) ?>"
                               ajax="true"><?php echo get_user_name($feed['targetUser']) ?></a>

                        </span>

        <?php endif ?>

        <?php if ($feed['shared']): ?>
            <?php echo $feed['shared_title'] ?>
        <?php endif ?>
        <?php if (isset($feed['tags-users'])): ?>
            <i class="ion-ios-arrow-thin-right"></i> <?php _lang('with'); ?>
            <?php if ($feed['tagsCount'] > 2): ?>

                <?php $firstUser = $feed['tags-users'][0] ?>
                <span data-type="user" data-id="<?php echo $firstUser['id'] ?>" class="preview-card">
                                <a ajax="true"
                                   href="<?php echo profile_url(null, $firstUser) ?>"><?php echo get_user_name($firstUser) ?></a>
                            </span>

                <?php _lang('and') ?> <a data-toggle="tooltip" data-placement="top"
                                         title="<?php $i = 1;
                                         foreach ($feed['tags-users'] as $user): ?>
                                    <?php if ($i > 1): ?>
                                        <?php echo get_user_name($user) ?>,
                                    <?php endif ?>
                                <?php $i++;endforeach ?>"
                                         href=""><?php echo(count($feed['tags-users']) - 1) ?> <?php _lang('other-people') ?></a>
            <?php else: ?>
                <?php $i = 1;
                foreach ($feed['tags-users'] as $user): ?>
                    <?php echo ($i == 2) ? ' ' . lang('and') . ' ' : null ?>
                    <span data-type="user" data-id="<?php echo $user['id'] ?>" class="preview-card">
                                    <a ajax="true"
                                       href="<?php echo profile_url(null, $user) ?>"><?php echo get_user_name($user) ?></a>
                                </span>

                    <?php $i++; endforeach ?>
            <?php endif ?>
        <?php endif ?>
        <?php theme_extend('feed-title', null, array($feed)) ?>

    </div>

    <span style='font-size: 14px; margin-left: 2px'><i style='color: <?php echo config('booster-star-color','#26A65B')?>' class='ion-android-star'></i> <?php echo lang('booster::sponsored') ?></span>
    <?php if ($feed['location']): ?>
        - <i class="ion-ios-location"></i> <span
            style="color:grey;font-size:12px"><?php echo $feed['location'] ?></span>
    <?php endif ?>
    - <span class="dropdown">
                                <a id="feed-privacy-icon-<?php echo $feed['feed_id'] ?>" data-toggle="dropdown"
                                   class="dropdown-button" href="#">
                                    <?php if ($feed['privacy'] == 1): ?>
                                        <i class="ion-android-globe"></i>
                                    <?php elseif ($feed['privacy'] == 2): ?>
                                        <i class="ion-ios-people"></i>
                                    <?php
                                    else: ?>
                                        <i class="ion-android-lock"></i>
                                    <?php endif ?>
                                </a>
        <?php if (can_edit_feed_privacy($feed)): ?>
            <ul id="feed-privacy-dropdown-<?php echo $feed['feed_id'] ?>" class="dropdown-menu">
                <li><a data-icon="ion-android-globe" data-id="1" data-feed="<?php echo $feed['feed_id'] ?>"
                       class="dropdown-item feed-privacy-toggle" href="javascript:void(0)"><i
                            class="ion-android-globe"></i> <?php echo lang('public') ?></a></li>
                <li><a data-icon="ion-ios-people" data-id="2" data-feed="<?php echo $feed['feed_id'] ?>"
                       class="dropdown-item feed-privacy-toggle" href="javascript:void(0)">
                        <i class="ion-ios-people"></i>
                        <?php echo (config('relationship-method', 3) == 1) ? lang('feed::followers-only') : lang('feed::friends-only') ?>
                    </a></li>
                <li><a data-icon="ion-android-lock" data-feed="<?php echo $feed['feed_id'] ?>" data-id="3"
                       class="dropdown-item feed-privacy-toggle" href="javascript:void(0)"><i
                            class="ion-android-lock"></i> <?php echo lang('feed::only-me') ?></a></li>
            </ul>
        <?php endif ?>
                            </span>
    <?php if ($feed['edited']): ?>
        - <?php echo lang('feed::edited') ?>
    <?php endif ?>

    <?php if (config('enable-feed-social-share', true) and $feed['privacy'] == 1): ?>
        <span class="feed-social-share-link">
                        <i class="ion-android-share"></i>
                        <a href="javascript:void(0)" onclick="return window.open(
                            'http://www.facebook.com/sharer.php?u=<?php echo url_to_pager('view-post', array('id' => $feed['feed_id'])) ?>'
                            , 'targetWindow', 'width=600,height=400')" class="" data-toggle="tooltip"
                           title="<?php _lang('feed::share-to-facebook') ?>"><i class="ion-social-facebook"></i></a>
                        <a href="javascript:void(0)" onclick="return window.open(
                            'http://twitter.com/share?url=<?php echo url_to_pager('view-post', array('id' => $feed['feed_id'])) ?>'
                            , 'targetWindow', 'toolbar=no,location=no,status=no,scrollbar=yes,resizable=no,width=600,height=400')"
                           data-toggle="tooltip" title="<?php _lang('feed::share-to-twitter') ?>"><i
                                class="ion-social-twitter"></i></a>
                        <a href="javascript:void(0)" onclick="return window.open(
                            'https://plus.google.com/share?url=<?php echo url_to_pager('view-post', array('id' => $feed['feed_id'])) ?>'
                            , 'targetWindow', 'toolbar=no,location=no,status=no,scrollbar=yes,resizable=no,width=600,height=400')"
                           data-toggle="tooltip" title="<?php _lang('feed::share-to-googleplus') ?>"><i
                                class="ion-social-googleplus"></i></a>
                        <a href="javascript:void(0)" onclick="return window.open(
                            'http://www.linkedin.com/shareArticle?mini=true&url=<?php echo url_to_pager('view-post', array('id' => $feed['feed_id'])) ?>'
                            , 'targetWindow', 'toolbar=no,location=no,status=no,scrollbar=yes,resizable=no,width=600,height=400')"
                           data-toggle="tooltip" title="<?php _lang('feed::share-to-linkedin') ?>"><i
                                class="ion-social-linkedin"></i></a>

                    </span>
    <?php endif ?>


    <div class="feed-menu dropdown">
        <?php if (is_feed_pinned($feed['feed_id'])): ?>
            <i data-toggle="tooltip" title="<?php _lang('feed::pinned-post') ?>"
               class="ion-bookmark feed-pinned"></i>
        <?php endif ?>
        <a href="" class="dropdown-toggle" data-toggle="dropdown" style="font-size: 30px;margin-right: 5px"><i
                class="ion-android-more-vertical"></i></a>
        <ul style="width: 220px;float: right" id="<?php echo $feed['feed_id'] ?>-feed-menu"
            class="dropdown-menu dropdown-menu-right left">




            <?php if (is_loggedIn()): ?>

                <li>
                    <a
                        class="dropdown-item"
                        data-on="<?php echo lang('feed::get-notifications') ?>"
                        data-off="<?php echo lang('feed::stop-notifications') ?>"
                        id="feed-notifications-<?php echo $feed['feed_id'] ?>"
                        data-turned="<?php echo (has_subscribed('feed', $feed['feed_id'])) ? 1 : 0 ?>"
                        onclick="return toggle_feed_notification('<?php echo $feed['feed_id'] ?>')"
                        href="">
                        <i class="ion-android-notifications-none"></i>
                        <?php if (has_subscribed('feed', $feed['feed_id'])): ?>
                            <?php echo lang('feed::stop-notifications') ?>
                        <?php else: ?>
                            <?php echo lang('feed::get-notifications') ?>
                        <?php endif ?>
                    </a>
                </li>


                <li>
                    <a onclick="return process_user_save(this, 'feed', '<?php echo $feed['feed_id'] ?>')" href=""
                       class="dropdown-item user-save"
                       data-status="<?php echo (user_saved('feed', $feed['feed_id'])) ? 1 : 0 ?>">
                        <i class="ion-android-bookmark"></i>
                        <span><?php echo (user_saved('feed', $feed['feed_id'])) ? lang('unsave-post') : lang('save-post') ?></span>
                    </a>
                </li>

                <li class="divider"></li>
                <?php if (can_edit_feed($feed)): ?>
                    <li><a class="dropdown-item" onclick="return delete_feed('<?php echo $feed['feed_id'] ?>')"
                           href=""><i class="ion-android-delete"></i> <?php echo lang('feed::delete-post') ?></a>
                    </li>
                    <?php if (config('allow-feed-editing', true)): ?>
                        <li><a class="dropdown-item"
                               onclick="return show_feed_edit_form('<?php echo $feed['feed_id'] ?>')" href="#!"><i
                                    class="ion-edit"></i> <?php echo lang('feed::edit-post') ?></a></li>
                    <?php endif ?>
                <?php endif ?>


            <?php endif ?>

            <li><a class="dropdown-item"
                   href="<?php echo url_to_pager('view-post', array('id' => $feed['feed_id'])) ?>" ajax="true"><i
                        class="ion-eye"></i> <?php _lang('feed::view-post') ?></a></li>
        </ul>
    </div>
</div>
</div>

<form onsubmit="return save_feed('<?php echo $feed['feed_id'] ?>')" id="feed-edit-form-<?php echo $feed['feed_id'] ?>"
      class="feed-edit-form" action="post">
    <textarea name="text" class="auto-grow-input" data-height="50px"><?php echo $feed['feed_content'] ?></textarea>
    <button class="btn btn-info btn-sm"><?php echo lang('save') ?></button>
    <a onclick="return show_feed_edit_form('<?php echo $feed['feed_id'] ?>')" href=""
       class="btn-flat"><?php echo lang('cancel') ?></a>
    <img src="<?php echo img('images/loading.gif') ?>" class="feed-edit-form-indicator"/>
</form>

<?php echo view('feed::feed-content', array('feed' => $feed)) ?>
<?php if ($feed['shared']): ?>
    <div class="feed-shared-container">
        <div class="media media-md">
            <div class="media-left">
                <div class="media-object"><a ajax="true" href="<?php echo $feed['shared-feed']['publisher']['url'] ?>">
                        <img src="<?php echo $feed['shared-feed']['publisher']['avatar'] ?>"/></a></div>
            </div>
            <div class="media-body">
                <div class="feed-title">
                                <span data-type='<?php echo $feed['shared-feed']['entity_type'] ?>'
                                      data-id='<?php echo $feed['shared-feed']['entity_id'] ?>' class='preview-card'>
                                    <a ajax="true" href="<?php echo $feed['shared-feed']['publisher']['url'] ?>">
                                        <?php echo $feed['shared-feed']['publisher']['name'] ?>
                                        <?php echo verify_badge($feed['shared-feed']['publisher']) ?>
                                    </a>
                                </span>

                    <?php theme_extend('feed-title', null, array($feed['shared-feed'])) ?>
                </div>
                <span class="feed-time"> <span class="timeago "
                                               title="<?php echo date('c', $feed['shared-feed']['time']) ?>"><?php echo date('c', $feed['shared-feed']['time']) ?></span></span>

                <?php if ($feed['shared-feed']['edited']): ?>
                    - <?php echo lang('feed::edited') ?>
                <?php endif ?>
                <?php if ($feed['shared-feed']['location']): ?>
                    <i class="ion-ios-location"></i> <?php echo $feed['location'] ?>
                <?php endif ?>

            </div>
        </div>
        <?php echo view('feed::feed-content', array('feed' => $feed['shared-feed'])) ?>
    </div>
<?php endif ?>

<?php if (plugin_loaded('like') and config('feed-like-type', 'regular') != 'regular'): ?>
    <div class="reactors reactors-feed-<?php echo $feed['feed_id'] ?>">
        <?php echo view('like::reacts', array('type' => 'feed', 'type_id' => $feed['feed_id'])) ?>
    </div>
<?php endif ?>
<div class="feed-footer">
    <div class="">
        <ul class=" feed-footer-menu clearfix">
            <?php if (plugin_loaded('like')): ?>
                <?php load_functions('like::like'); ?>


                <?php if (config('feed-like-type', 'regular') == 'regular'): ?>

                    <li><a onclick="return like_item('feed', '<?php echo $feed['feed_id'] ?>')"
                           data-status="<?php echo (has_liked('feed', $feed['feed_id'])) ? '1' : 0 ?>"
                           class=" like-button-feed-<?php echo $feed['feed_id'] ?> like-button <?php echo (has_liked('feed', $feed['feed_id'])) ? 'liked' : null ?>"
                           href=""> <i class="ion-thumbsup"></i> <span
                                class="hidden-md-down"><?php echo lang('like::like') ?></span></a></li>
                    <?php if (config('enable-dislike', false)): ?>
                        <li><a id="" onclick="return dislike_item('feed', '<?php echo $feed['feed_id'] ?>')"
                               data-status="<?php echo (has_disliked('feed', $feed['feed_id'])) ? '1' : 0 ?>"
                               class="dislike-button-feed-<?php echo $feed['feed_id'] ?> like-button <?php echo (has_disliked('feed', $feed['feed_id'])) ? 'disliked' : null ?>"
                               href=""> <i class="ion-thumbsdown"></i> <span
                                    class="hidden-md-down"><?php echo lang('like::dislike') ?></span></a></li>
                    <?php endif ?>
                <?php else: ?>
                    <li class="feed-react">
                        <div class="react-items react-items-<?php echo $feed['feed_id'] ?>" id="">
                            <ul>
                                <li><a data-type="feed" data-target="<?php echo $feed['feed_id'] ?>" href=""
                                       data-code="1" data-toggle="tooltip" title="<?php _lang('like::like') ?>"><img
                                            src="<?php echo img('images/reaction/like.png') ?>"/></a></li>
                                <li><a data-type="feed" data-target="<?php echo $feed['feed_id'] ?>" href=""
                                       data-code="4" data-toggle="tooltip" title="<?php _lang('like::love') ?>"><img
                                            src="<?php echo img('images/reaction/love.png') ?>"/></a></li>
                                <li><a data-type="feed" data-target="<?php echo $feed['feed_id'] ?>" href=""
                                       data-code="5" data-toggle="tooltip" title="<?php _lang('like::haha') ?>"><img
                                            src="<?php echo img('images/reaction/haha.png') ?>"/></a></li>
                                <li><a data-type="feed" data-target="<?php echo $feed['feed_id'] ?>" href=""
                                       data-code="6" data-toggle="tooltip" title="<?php _lang('like::yay') ?>"><img
                                            src="<?php echo img('images/reaction/yay.png') ?>"/></a></li>
                                <li><a data-type="feed" data-target="<?php echo $feed['feed_id'] ?>" href=""
                                       data-code="7" data-toggle="tooltip" title="<?php _lang('like::wow') ?>"><img
                                            src="<?php echo img('images/reaction/wow.png') ?>"/></a></li>
                                <li><a data-type="feed" data-target="<?php echo $feed['feed_id'] ?>" href=""
                                       data-code="8" data-toggle="tooltip" title="<?php _lang('like::sad') ?>"><img
                                            src="<?php echo img('images/reaction/sad.png') ?>"/></a></li>
                                <li><a data-type="feed" data-target="<?php echo $feed['feed_id'] ?>" href=""
                                       data-code="9" data-toggle="tooltip" title="<?php _lang('like::angry') ?>"><img
                                            src="<?php echo img('images/reaction/angry.png') ?>"/></a></li>

                            </ul>
                        </div>
                        <a data-type="feed" data-target="<?php echo $feed['feed_id'] ?>"
                           data-status="<?php echo (has_reacted('feed', $feed['feed_id'])) ? '1' : 0 ?>"
                           class=" react-button-feed-<?php echo $feed['feed_id'] ?> react-button <?php echo (has_reacted('feed', $feed['feed_id'])) ? 'liked' : null ?>"
                           href=""> <i class="ion-thumbsup"></i> <span
                                class="hidden-md-down"><?php echo lang('like::like') ?></span></a>
                    </li>
                <?php endif ?>
            <?php endif ?>
            <?php if (config('allow-feed-sharing', true) and can_share_feed($feed)): ?>
                <li><a href="#!"
                       onclick="return share_feed('<?php echo $feed['feed_id'] ?>', '<?php echo lang('feed::share-warning-message') ?>')">
                        <i class="ion-android-share"></i> <span
                            class="hidden-md-down"><?php echo lang('feed::share') ?></span></a></li>
            <?php endif ?>


            <li class="pull-right" style="margin: 0">
                <ul class="feed-statistics">
                    <?php if (plugin_loaded('like') and config('feed-like-type', 'regular') == 'regular'): ?>
                        <li><a onclick="return show_likes('feed', '<?php echo $feed['feed_id'] ?>')" href=""> <i
                                    class="ion-thumbsup"></i> <span
                                    class="like-count-feed-<?php echo $feed['feed_id'] ?>"><?php echo count_likes('feed', $feed['feed_id']) ?></span></a>
                        </li>
                        <?php if (config('enable-dislike', false)): ?>
                            <li><a onclick="return show_dislikes('feed', '<?php echo $feed['feed_id'] ?>')" href=""> <i
                                        class="ion-thumbsdown"></i> <span
                                        class="dislike-count-feed-<?php echo $feed['feed_id'] ?>"><?php echo count_dislikes('feed', $feed['feed_id']) ?></span></a>
                            </li>
                        <?php endif ?>

                    <?php endif ?>

                    <?php if (plugin_loaded('comment')): ?>
                        <?php load_functions('comment::comment') ?>
                        <?php $countComments = count_comments('feed', $feed['feed_id']); ?>
                        <li><i class="ion-chatbubbles"></i> <span
                                class="comment-count-feed-<?php echo $feed['feed_id'] ?>"><?php echo ($countComments) ? $countComments : null ?></span>
                        </li>
                    <?php endif ?>
                    <?php if (config('allow-feed-sharing', true)): ?>
                        <li><a href="javascript::void(0)"> <i class="ion-android-share"></i></a> <span
                                id="feed-share-count-<?php echo $feed['feed_id'] ?>"><?php echo ($feed['shared_count']) ? $feed['shared_count'] : null ?></span>
                        </li>
                    <?php endif ?>
                </ul>
            </li>
        </ul>
    </div>
    <?php if (plugin_loaded('comment')): ?>
        <div class="feed-comment-container">

            <?php if ($countComments > config('feed-comment-limit', 3)): ?>
                <a id="comment-view-more-button-feed-<?php echo $feed['feed_id'] ?>"
                   class="comment-view-more-button comment-view-more-button-feed-<?php echo $feed['feed_id'] ?>"
                   onclick="return show_more_comment('feed', '<?php echo $feed['feed_id'] ?>', 'comment-view-more-indicator-<?php echo $feed['feed_id'] ?>')"
                   href=""><?php _lang('view-previous-comments') ?></a>
                <img class="comment-view-more-indicator" id="comment-view-more-indicator-<?php echo $feed['feed_id'] ?>"
                     src="<?php echo img('images/loading.gif') ?>"/>
            <?php endif ?>
            <div data-offset="<?php echo config('feed-comment-limit', 3) ?>"
                 data-limit="<?php echo config('feed-comment-limit', 3) ?>"
                 class="comment-lists comment-lists-feed-<?php echo $feed['feed_id'] ?>" id="">
                <?php foreach (get_comments('feed', $feed['feed_id'], config('feed-comment-limit', 3), 0, $feed) as $comment): ?>
                    <?php echo view('comment::display', array('comment' => $comment)) ?>
                <?php endforeach; ?>
            </div>
            <?php echo view('comment::editor', array(
                'typeId' => $feed['feed_id'],
                'type' => 'feed',
                'entityId' => $entityId,
                'entityType' => $entityType,
                'avatar' => $avatar,
                'textLimit' => (config('enable-feed-text-limit', false)) ? config('maximum-feed-text-limit', 150) : false))?>

        </div>
    <?php endif ?>
</div>
</div>


</div>
</div>