<div class="box">
    <div class="global-filter-container" data-url="<?php echo url('pages')?>">
        <div class="row">
            <div class="col-sm-6">
                <h3><?php _lang('page::pages')?></h3>
            </div>
            <div class="col-sm-6">
                <form id="video-list-search" method="post" onsubmit=" return run_global_filter()" action="" class="form-inline pull-right">
					<?php CSRFProtection::embed() ?>
                    <input type="hidden" class="video-type-input filter-input" data-name="type" value="<?php echo input('type','browse')?>"/>
                    <input value="<?php echo input('term')?>" type="text" class="form-control filter-input" data-name="term" placeholder="<?php _lang('page::find-pages')?>"/>
                    <button class="btn btn-info"><i class="ion-search"></i></button>
                </form>
            </div>
        </div>
        <div class="  filter-pane">
            <select id="video-category-list" onchange="return run_global_filter()" data-name="category" class="c-select filter-input" >
                <option <?php echo (input('category', 'all') == 'all') ? 'selected'  : null?>  value="all"><?php _lang('video::all-categories')?></option>
                <?php foreach(get_page_categories() as $category):?>
                    <option <?php echo (input('category', 'all') == $category['category_id']) ? 'selected'  : null?> value="<?php echo $category['category_id']?>"><?php _lang($category['category_title'])?></option>
                <?php endforeach?>
            </select>

            <select id="video-filter-select" onchange="return run_global_filter()" data-name="filter" class="c-select filter-input">
                <option value="all"><?php _lang('all')?></option>
                <option <?php echo (input('filter') == 'featured') ? 'selected' : null?> value="featured"><?php _lang('featured')?></option>
            </select>

            <div class="list-layout-type">
                <a href="" onclick="return change_listing_layout('#group-list-container', 'list', 'page_set_list_type')"><i class="ion-ios-list-outline"></i></a>
                <a href="" onclick="return change_listing_layout('#group-list-container', 'grid', 'page_set_list_type')"><i class="ion-android-apps"></i></a>
            </div>
        </div>
    </div>
    <div id="group-list-container" class="box-content clearfix <?php echo ($list_type == 'list') ? 'list-listing-container' : 'grid-listing-container' ?>">
        <?php foreach($pages->results() as $page):?>
            <?php echo view('page::display', array('page' => $page))?>
        <?php endforeach?>
    </div>
    <div class="box-content">
        <?php if($pages->total):?>

            <?php echo $pages->append(array('term' => input('term'), 'filter' => input('filter', 'all'), 'type' => input('type', 'browse'), 'category' => input('category')))->links()?>
        <?php else:?>
            <?php _lang('page::no-pages-found')?>
        <?php endif?>
    </div>
</div>