<div class="box">
    <div class="title"><?php _lang("blog::blogs")?></div>
    <div class="box-content">
        <?php if($blogs->total):?>
            <?php foreach($blogs->results() as $blog):$user = find_user($blog['user_id'])?>
                <div  class="media media-lg">
                    <div class="media-left">
                        <div class="media-object">
                            <img src="<?php echo ($blog['image']) ? url_img($blog['image'], 700) : get_avatar(200, $user)?>"/>
                        </div>
                    </div>
                    <div class="media-body">
                        <h4 class="media-heading"><a ajax="true" href="<?php echo url('blog/'.$blog['slug'])?>"><?php echo $blog['title']?></a></h4>
                                <span class="help-block" style="display: block">
                                    <?php _lang('blog::posted-by')?> : <a href="<?php echo profile_url(null, $user)?>"><?php echo get_user_name($user)?></a>
                                    <?php _lang('blog::on')?> <?php echo date('M j , y  h:i A', $blog['time'])?>
                                </span>
                        <div><?php echo strip_tags(str_limit($blog['content'], 100))?></div>
                    </div>
                </div>
            <?php endforeach?>

            <?php echo $blogs->links()?>
        <?php else:?>

            <div class="alert alert-info"><?php _lang('blog::blogs-list-empty')?></div>
        <?php endif?>
    </div>
</div>